const same = (items) => ({ admin: items, personal: items });

export const ASSISTANT_SCREENS = Object.freeze({
  dashboard: { description: 'Resumen de la actividad disponible para el rol actual.', capabilities: same(['Consultar indicadores', 'Usar accesos rápidos', 'Abrir módulos de trabajo']), nextStep: 'Selecciona en el menú el módulo relacionado con la tarea que deseas realizar.' },
  pacientes: { description: 'Administración y consulta del listado de pacientes.', capabilities: { admin: ['Buscar pacientes', 'Registrar pacientes', 'Abrir fichas', 'Editar', 'Desactivar pacientes'], personal: ['Buscar pacientes', 'Registrar pacientes', 'Abrir fichas', 'Editar información permitida'] }, nextStep: 'Si la persona es nueva, primero búscala por CI para evitar duplicados; si ya existe, abre su ficha.', tips: ['El sistema advierte cuando el CI ya pertenece a un paciente activo o inactivo.'], warnings: { personal: ['Desactivar pacientes es una acción administrativa.'] } },
  'detalle-paciente': { description: 'Ficha de un paciente con accesos a su información relacionada.', capabilities: same(['Consultar la ficha', 'Revisar información registrada', 'Volver al listado de pacientes']), nextStep: 'Después de revisar la ficha, abre el módulo clínico correspondiente para consultar historias, citas o sesiones.' },
  'resumen-pacientes': { description: 'Resumen relacionado de historias, sesiones, citas y documentos de pacientes.', capabilities: same(['Buscar pacientes', 'Filtrar registros', 'Consultar actividad relacionada']), nextStep: 'Selecciona un paciente y aplica los filtros necesarios para revisar su información relacionada.', warnings: { personal: ['La información financiera no se muestra al rol PERSONAL.'] } },
  historias: { description: 'Creación, consulta y administración de historias clínicas.', capabilities: { admin: ['Crear historia clínica', 'Consultar y editar', 'Programar sesiones', 'Imprimir', 'Anular o restaurar'], personal: ['Crear historia clínica', 'Consultar y editar historias activas', 'Programar sesiones', 'Imprimir'] }, nextStep: 'Después de completar la evaluación, revisa el plan de tratamiento y las sesiones contratadas antes de programarlas.', warnings: { personal: ['Anular y restaurar historias está reservado al ADMIN.'] } },
  'detalle-historia': { description: 'Detalle documental de una historia clínica.', capabilities: same(['Consultar la evaluación', 'Revisar el plan de tratamiento', 'Consultar sesiones vinculadas', 'Imprimir o guardar como PDF']), nextStep: 'Revisa la evaluación y el plan de tratamiento; después consulta o programa las sesiones relacionadas.' },
  evoluciones: { description: 'Seguimiento clínico vinculado a historias y sesiones.', capabilities: { admin: ['Crear, consultar y editar evoluciones', 'Filtrar registros', 'Anular evoluciones', 'Abrir la historia relacionada'], personal: ['Crear, consultar y editar evoluciones activas', 'Filtrar registros', 'Abrir la historia relacionada'] }, nextStep: 'Selecciona una historia activa y registra el seguimiento de la sesión correspondiente.', warnings: { personal: ['La anulación de evoluciones es administrativa.'] } },
  agenda: { description: 'Consulta y administración de citas programadas.', capabilities: same(['Usar Lista de citas o Calendario', 'Crear citas', 'Confirmar', 'Reprogramar', 'Cancelar', 'Registrar inasistencia']), nextStep: 'Busca primero al paciente y revisa el Calendario; después crea o actualiza la cita necesaria.', tips: ['Una cita organiza fecha y horario; la sesión clínica documenta la atención realizada.'] },
  sesiones: { description: 'Registro de la atención y evolución realizada en cada sesión.', capabilities: { admin: ['Registrar y editar sesiones', 'Controlar asistencia', 'Registrar evolución, dolor, técnicas, medios físicos y fármacos', 'Consultar información de pago'], personal: ['Registrar y editar sesiones', 'Controlar asistencia', 'Registrar evolución, dolor, técnicas, medios físicos y fármacos'] }, nextStep: 'Selecciona una historia activa o programación y registra la asistencia; si asistió, completa la evolución clínica.', warnings: { personal: ['Los montos, pagos y saldos son información administrativa.'] } },
  'sesiones-semanales': { description: 'Resumen semanal de sesiones y asistencia.', capabilities: { admin: ['Consultar y recalcular el resumen', 'Exportar', 'Revisar información clínica y financiera'], personal: ['Consultar y recalcular el resumen', 'Exportar información clínica permitida'] }, nextStep: 'Selecciona el período, actualiza o recalcula el resumen y después exporta si lo necesitas.', warnings: { personal: ['La exportación para PERSONAL excluye información financiera.'] } },
  informes: { description: 'Creación y gestión de informes médicos vinculados con información clínica.', capabilities: same(['Crear informe', 'Editar', 'Consultar', 'Imprimir', 'Descargar PDF']), nextStep: 'Selecciona la información relacionada, completa el informe y revisa el documento antes de imprimir o descargar.' },
  consentimiento: { description: 'Gestión del documento de consentimiento informado.', capabilities: same(['Crear', 'Consultar', 'Editar', 'Imprimir o guardar el documento']), nextStep: 'Selecciona al paciente, completa el documento y revísalo antes de imprimir.' },
  'signos-vitales': { description: 'Registro documental de signos vitales.', capabilities: same(['Crear registro', 'Consultar', 'Editar', 'Imprimir']), nextStep: 'Crea el documento, completa los campos disponibles y guarda el registro.' },
  farmacos: { description: 'Registro clínico de productos o fármacos administrados.', capabilities: { admin: ['Registrar producto, presentación, dosis, volumen, cantidad y vía', 'Registrar motivo y observaciones', 'Gestionar información de pago'], personal: ['Registrar producto, presentación, dosis, volumen, cantidad y vía', 'Registrar motivo y observaciones clínicas'] }, nextStep: 'Agrega los productos administrados, completa la vía, el motivo y las observaciones clínicas, y guarda el documento.', warnings: { personal: ['PERSONAL no recibe información de costos, pagos o saldos.'] } },
  'planillas-atencion': { description: 'Creación y consulta de planillas documentales de atención.', capabilities: same(['Crear planilla', 'Editar', 'Consultar', 'Imprimir', 'Descargar PDF']), nextStep: 'Selecciona el registro relacionado, completa la planilla y revisa el documento antes de descargarlo.' },
  actividades: { description: 'Gestión de tareas extra propias y actividad relacionada.', capabilities: same(['Ver actividades propias', 'Crear tarea extra', 'Editar', 'Completar', 'Eliminar una tarea propia']), nextStep: 'Crea una tarea extra si falta una actividad; si ya existe, actualiza su estado desde las acciones.' },
  notificaciones: { description: 'Bandeja de avisos generados por la actividad del sistema.', capabilities: same(['Consultar notificaciones', 'Marcar como leída', 'Abrir una referencia relacionada cuando existe']), nextStep: 'Abre la notificación pendiente y revisa su referencia cuando esté disponible.' },
  'recepcion-whatsapp': { description: 'Bandeja de solicitudes derivadas desde WhatsApp.', capabilities: { admin: ['Ver y tomar solicitudes', 'Cambiar prioridad', 'Guardar observaciones', 'Resolver y cerrar'], personal: ['Ver y tomar solicitudes', 'Guardar observaciones', 'Resolver y cerrar según su estado'] }, nextStep: 'Toma una solicitud pendiente; durante la atención guarda una observación o resolución y después ciérrala.', warnings: { personal: ['El cambio administrativo de prioridad está reservado al ADMIN.'] } },
  'resumen-diario': { description: 'Resumen diario clínico y operativo disponible para el rol actual.', capabilities: { admin: ['Consultar actividad clínica y operativa', 'Revisar el resumen administrativo disponible', 'Imprimir o exportar'], personal: ['Consultar actividad clínica y operativa permitida', 'Imprimir o exportar información permitida'] }, nextStep: 'Selecciona la fecha o filtros necesarios y revisa el resumen generado.', warnings: { personal: ['El resumen de PERSONAL no incluye información financiera.'] } },
  blog: { description: 'Gestión de publicaciones y borradores del blog.', capabilities: same(['Crear artículo', 'Editar artículos propios', 'Previsualizar', 'Publicar según permisos']), nextStep: 'Crea un borrador, revisa la vista previa y publícalo cuando el contenido esté listo.' },
  'nuevo-blog': { description: 'Formulario de creación de una publicación.', capabilities: same(['Completar el artículo', 'Guardar borrador', 'Previsualizar']), nextStep: 'Completa el contenido y guarda primero el borrador para poder revisarlo.' },
  'editar-blog': { description: 'Formulario de edición de una publicación existente.', capabilities: same(['Editar contenido propio', 'Guardar cambios', 'Previsualizar']), nextStep: 'Revisa los cambios en la vista previa antes de publicar.' },
  'vista-previa-blog': { description: 'Vista previa de una publicación del blog.', capabilities: same(['Revisar el contenido', 'Volver a editar']), nextStep: 'Si el contenido necesita ajustes, vuelve a editarlo; si está listo, usa la acción de publicación disponible.' },
  finanzas: { description: 'Administración de planillas de pagos y control financiero.', capabilities: { admin: ['Gestionar pagos y deudas', 'Consultar recibos, comprobantes y arqueos', 'Exportar información'], personal: [] }, nextStep: 'Selecciona la operación financiera necesaria y revisa sus datos antes de confirmar.', adminOnly: true },
  usuarios: { description: 'Administración de cuentas y personal del sistema.', capabilities: { admin: ['Crear y editar cuentas', 'Administrar personal', 'Revisar estados de usuario'], personal: [] }, nextStep: 'Busca la cuenta o persona y utiliza la acción administrativa correspondiente.', adminOnly: true },
  sueldos: { description: 'Administración de planillas mensuales de sueldos.', capabilities: { admin: ['Crear y editar borradores', 'Cerrar o reabrir planillas', 'Imprimir, descargar PDF o exportar Excel', 'Anular'], personal: [] }, nextStep: 'Crea o abre un borrador, agrega el personal activo y revisa la vista previa antes de cerrar.', adminOnly: true },
  'roles-permisos': { description: 'Consulta de la política de acceso aplicada por rol.', capabilities: { admin: ['Consultar módulos y acciones permitidas por rol'], personal: [] }, nextStep: 'Selecciona el módulo que deseas revisar dentro de la matriz de permisos.', adminOnly: true },
  'monitoreo-whatsapp': { description: 'Supervisión técnica de la integración de WhatsApp.', capabilities: { admin: ['Consultar estado operativo e indicadores de monitoreo'], personal: [] }, nextStep: 'Revisa el estado general y los indicadores para identificar incidencias.', adminOnly: true },
  'categorias-blog': { description: 'Administración de categorías para publicaciones.', capabilities: { admin: ['Crear, editar y eliminar categorías'], personal: [] }, nextStep: 'Busca una categoría existente antes de crear o modificar otra.', adminOnly: true }
});

export function getAssistantScreen(screen) {
  return ASSISTANT_SCREENS[screen] || null;
}
