const BOTH = Object.freeze(['admin', 'personal']);
const ADMIN = Object.freeze(['admin']);

const overview = (module, label, permission, answer, roles = BOTH) => ({
  id: `${module}.overview`, module, screen: null, roles, permission,
  title: `Ayuda sobre ${label}`,
  intents: ['que puedo hacer aqui', 'para que sirve esta pantalla', `ayuda ${label}`],
  keywords: ['ayuda', 'pantalla', label], answer,
  steps: [], route: null, question: '¿Qué puedo hacer aquí?'
});

const guide = (id, module, permission, title, intents, keywords, answer, steps, route, question, roles = BOTH, extra = {}) => ({
  id, module, screen: null, roles, permission, title, intents, keywords, answer, steps, route, question, ...extra
});

const navigationGuide = (id, module, permission, title, names, answer, route, roles = BOTH) => guide(
  `navigation.${id}`,
  module,
  permission,
  title,
  names.flatMap((name) => [`ir a ${name}`, `abre ${name}`, `llevame a ${name}`, `donde esta ${name}`, `quiero ver ${name}`]),
  names,
  answer,
  [],
  route,
  null,
  roles
);

const navigationEntries = [
  navigationGuide('panel', 'dashboard', 'dashboard', 'Panel principal', ['panel', 'inicio', 'dashboard'], 'Puedes regresar al Panel principal.', '/'),
  navigationGuide('pacientes', 'pacientes', 'pacientes', 'Pacientes', ['pacientes', 'paciente'], 'Puedes registrar y consultar pacientes desde el módulo Pacientes.', '/pacientes'),
  navigationGuide('historias', 'historias', 'historias', 'Historias clínicas', ['historias', 'historias clinicas'], 'Puedes consultar y gestionar evaluaciones desde Historias clínicas.', '/historias-clinicas'),
  navigationGuide('agenda', 'agenda', 'agenda', 'Citas / Agenda', ['agenda', 'citas', 'cita'], 'Puedes gestionar las citas desde Citas / Agenda.', '/citas'),
  navigationGuide('sesiones', 'sesiones', 'sesiones', 'Sesiones', ['sesiones', 'sesion'], 'Puedes registrar y consultar atenciones desde Sesiones.', '/sesiones'),
  navigationGuide('informes', 'informes', 'informes', 'Informes médicos', ['informes', 'informes medicos'], 'Puedes gestionar documentos desde Informes médicos.', '/informes-medicos'),
  navigationGuide('actividades', 'actividades', 'actividadesPropias', 'Mis actividades', ['actividades', 'mis actividades', 'tareas'], 'Tus tareas se encuentran en Mis actividades.', '/personal/actividades'),
  navigationGuide('notificaciones', 'notificaciones', null, 'Notificaciones', ['notificaciones', 'avisos'], 'Puedes consultar tus avisos en Notificaciones.', '/notificaciones'),
  navigationGuide('recepcion-whatsapp', 'recepcion-whatsapp', 'recepcionWhatsapp', 'Recepción WhatsApp', ['recepcion whatsapp', 'solicitudes whatsapp'], 'Puedes atender solicitudes desde Recepción WhatsApp.', '/whatsapp/recepcion'),
  navigationGuide('evoluciones', 'evoluciones', 'evolutivos', 'Evolutivos clínicos', ['evoluciones', 'evolutivos'], 'Puedes consultar los registros desde Evolutivos clínicos.', '/evolutivos-clinicos'),
  navigationGuide('semanales', 'sesiones-semanales', 'sesionesSemanales', 'Sesiones semanales', ['sesiones semanales'], 'Puedes consultar el período desde Sesiones semanales.', '/sesiones-semanales'),
  navigationGuide('planillas-atencion', 'planillas-atencion', 'planillasAtencion', 'Planillas de atención', ['planillas de atencion'], 'Puedes gestionar estos documentos desde Planillas de atención.', '/planillas-atencion'),
  navigationGuide('blog', 'blog', 'blogAdministracion', 'Blog', ['blog', 'articulos'], 'Puedes gestionar tus publicaciones desde Blog.', '/blog'),
  navigationGuide('finanzas', 'finanzas', 'finanzas', 'Control financiero', ['finanzas', 'pagos', 'deudores', 'arqueos', 'recibos', 'comprobantes'], 'Puedes gestionar la información autorizada desde Control financiero.', '/control-financiero/planilla-pagos', ADMIN),
  navigationGuide('usuarios', 'usuarios', 'usuarios', 'Usuarios', ['usuarios', 'cuentas'], 'Puedes administrar las cuentas desde Usuarios.', '/usuarios', ADMIN),
  navigationGuide('sueldos', 'sueldos', 'sueldos', 'Planillas de sueldos', ['sueldos', 'planillas de sueldos', 'salarios'], 'Puedes consultar las planillas laborales desde Planillas de sueldos.', '/personal/planilla', ADMIN),
  navigationGuide('roles', 'roles-permisos', 'rolesPermisos', 'Roles y permisos', ['roles', 'permisos', 'roles y permisos'], 'Puedes consultar la política de acceso desde Roles y permisos.', '/roles-permisos', ADMIN),
  navigationGuide('monitoreo', 'monitoreo-whatsapp', 'monitoreoWhatsapp', 'Monitoreo WhatsApp', ['monitoreo whatsapp', 'monitoreo de whatsapp'], 'Puedes supervisar la integración desde Monitoreo WhatsApp.', '/whatsapp/monitoring', ADMIN),
  navigationGuide('categorias', 'categorias-blog', 'blogCategorias', 'Categorías del blog', ['categorias del blog', 'categorias blog'], 'Puedes administrar las categorías desde Categorías del blog.', '/blog/categorias', ADMIN)
];

const overviews = [
  overview('dashboard', 'Panel principal', 'dashboard', 'El Panel principal resume la actividad disponible para tu rol y ofrece accesos rápidos a los módulos de trabajo.'),
  overview('pacientes', 'Pacientes', 'pacientes', 'En Pacientes puedes registrar, buscar, editar y consultar pacientes, además de abrir su ficha o el resumen general.'),
  overview('historias', 'Historias clínicas', 'historias', 'En Historias clínicas puedes crear evaluaciones, consultar o editar historias, programar sesiones e imprimir documentos según tus permisos.'),
  overview('agenda', 'Citas / Agenda', 'agenda', 'En Citas / Agenda puedes consultar la agenda, crear, confirmar, reprogramar o cancelar citas y registrar faltas según tus permisos.'),
  overview('sesiones', 'Sesiones', 'sesiones', 'En Sesiones puedes registrar la atención realizada, documentar la evolución y completar los datos clínicos disponibles.'),
  overview('evoluciones', 'Evolutivos clínicos', 'evolutivos', 'Esta pantalla permite consultar y trabajar con los evolutivos clínicos registrados.'),
  overview('informes', 'Informes médicos', 'informes', 'Aquí puedes crear, editar, imprimir y descargar informes médicos según tus permisos.'),
  overview('sesiones-semanales', 'Sesiones semanales', 'sesionesSemanales', 'Aquí puedes consultar el registro semanal, recalcularlo y exportar la información permitida para tu rol.'),
  overview('planillas-atencion', 'Planillas de atención', 'planillasAtencion', 'Aquí puedes crear, editar y generar documentos PDF de las planillas de atención.'),
  overview('actividades', 'Mis actividades', 'actividadesPropias', 'En Mis actividades puedes gestionar tus tareas extra, cambiar su estado y editar o eliminar tus propios registros.'),
  overview('notificaciones', 'Notificaciones', null, 'Aquí puedes consultar los avisos del sistema y marcarlos como leídos.'),
  overview('recepcion-whatsapp', 'Recepción WhatsApp', 'recepcionWhatsapp', 'Esta bandeja reúne solicitudes recibidas por WhatsApp para tomarlas, responderlas y resolverlas.'),
  overview('blog', 'Blog', 'blogAdministracion', 'En Blog puedes crear borradores y gestionar tus propios artículos.'),
  overview('consentimiento', 'Consentimiento informado', 'documentosClinicos', 'Aquí puedes crear, consultar, editar e imprimir consentimientos informados.'),
  overview('signos-vitales', 'Signos vitales', 'documentosClinicos', 'Aquí puedes registrar y consultar documentos de signos vitales.'),
  overview('farmacos', 'Administración de fármacos', 'documentosClinicos', 'Aquí puedes registrar y consultar documentos de administración de fármacos según tus permisos.'),
  overview('resumen-diario', 'Resumen diario', 'resumenDiarioClinico', 'El resumen diario presenta la información clínica y operativa disponible para tu rol.'),
  overview('finanzas', 'Control financiero', 'finanzas', 'El área financiera permite administrar pagos, deudas, recibos, comprobantes y arqueos.', ADMIN),
  overview('usuarios', 'Usuarios y personal', 'usuarios', 'Esta pantalla permite administrar cuentas de usuario y la información de personal.', ADMIN),
  overview('sueldos', 'Planillas de sueldos', 'sueldos', 'Esta pantalla permite administrar planillas laborales y salariales.', ADMIN),
  overview('roles-permisos', 'Roles y permisos', 'rolesPermisos', 'Esta pantalla muestra la política de acceso aplicada a cada rol.', ADMIN),
  overview('monitoreo-whatsapp', 'Monitoreo WhatsApp', 'monitoreoWhatsapp', 'Esta pantalla permite supervisar el estado operativo de la integración de WhatsApp.', ADMIN),
  overview('categorias-blog', 'Categorías del blog', 'blogCategorias', 'Esta pantalla permite administrar las categorías usadas por las publicaciones.', ADMIN)
];

export const assistantKnowledge = Object.freeze([
  ...overviews,
  ...navigationEntries,
  guide('general.panel', 'general', null, 'Volver al panel', ['volver al panel', 'ir al inicio', 'llevame al inicio', 'regresar al dashboard'], ['panel', 'inicio', 'dashboard'], 'Puedes regresar al Panel principal desde el menú lateral.', ['Abre el menú lateral si estás en un dispositivo móvil.', 'Selecciona Panel principal.'], '/', '¿Cómo vuelvo al panel?'),
  guide('general.modulo', 'general', null, 'Encontrar un módulo', ['donde encuentro un modulo', 'buscar modulo', 'abrir modulo'], ['menu', 'modulo', 'encontrar'], 'Los módulos disponibles para tu rol aparecen en el menú lateral.', ['Abre el menú lateral.', 'Selecciona el módulo que necesitas.'], null, '¿Dónde encuentro un módulo?'),

  guide('pacientes.crear', 'pacientes', 'pacientes', 'Registrar un paciente', ['crear paciente', 'registrar paciente', 'nuevo paciente', 'agregar paciente'], ['paciente', 'crear', 'registrar', 'nuevo'], 'El registro se inicia desde el listado de Pacientes.', ['Ingresa a Pacientes.', 'Presiona Nuevo paciente.', 'Completa los datos requeridos.', 'Guarda el registro.'], '/pacientes', '¿Cómo registro un paciente?'),
  guide('pacientes.buscar', 'pacientes', 'pacientes', 'Buscar un paciente', ['buscar paciente', 'encontrar paciente'], ['buscar', 'paciente', 'nombre', 'documento'], 'Usa el buscador del listado de Pacientes para localizar una ficha por nombre o documento de identidad.', ['Ingresa a Pacientes.', 'Escribe el nombre o documento en el buscador.', 'Abre el resultado correspondiente.'], '/pacientes', '¿Cómo busco un paciente?'),
  guide('pacientes.editar', 'pacientes', 'pacientes', 'Editar un paciente', ['editar paciente', 'modificar paciente', 'actualizar paciente'], ['editar', 'paciente', 'modificar'], 'La edición se abre desde las acciones del paciente.', ['Busca al paciente.', 'Abre la acción Editar.', 'Actualiza los datos necesarios.', 'Guarda los cambios.'], '/pacientes', '¿Cómo edito un paciente?'),
  guide('pacientes.detalle', 'pacientes', 'pacientes', 'Ver detalle de un paciente', ['ver paciente', 'detalle paciente', 'ficha paciente'], ['detalle', 'ficha', 'paciente'], 'Abre la ficha del paciente desde el listado para consultar su detalle.', ['Busca al paciente.', 'Selecciona la opción para ver su detalle.'], '/pacientes', '¿Cómo veo el detalle?'),
  guide('pacientes.resumen', 'pacientes', 'pacientes', 'Ver resumen de pacientes', ['resumen pacientes', 'ver resumen paciente'], ['resumen', 'pacientes'], 'El resumen general está disponible en el módulo Resumen de pacientes.', ['Abre el menú lateral.', 'Selecciona Resumen de pacientes.'], '/resumen-pacientes', '¿Cómo veo el resumen?'),

  guide('historias.crear', 'historias', 'historias', 'Crear una historia clínica', ['crear historia clinica', 'nueva evaluacion', 'registrar historia'], ['historia', 'crear', 'evaluacion'], 'La historia se crea desde el listado de Historias clínicas.', ['Ingresa a Historias clínicas.', 'Presiona Nueva evaluación.', 'Selecciona al paciente y completa la evaluación.', 'Guarda la historia.'], '/historias-clinicas', '¿Cómo creo una historia clínica?'),
  guide('historias.editar', 'historias', 'historias', 'Editar una historia clínica', ['editar historia', 'modificar historia'], ['editar', 'historia'], 'Usa la acción Editar de la historia que deseas actualizar.', ['Localiza la historia.', 'Abre sus acciones y selecciona Editar.', 'Guarda los cambios.'], '/historias-clinicas', '¿Cómo edito una historia?'),
  guide('historias.ver', 'historias', 'historias', 'Consultar una historia clínica', ['ver historia', 'consultar historia', 'detalle historia'], ['ver', 'historia', 'detalle'], 'Puedes abrir el detalle desde el registro correspondiente del listado.', ['Busca la historia.', 'Selecciona Ver detalle.'], '/historias-clinicas', '¿Cómo veo una historia?'),
  guide('historias.programar', 'historias', 'historias', 'Programar sesiones', ['programar sesiones', 'agendar sesiones historia'], ['programar', 'sesiones', 'historia'], 'La programación de sesiones se abre desde las acciones de la historia.', ['Localiza la historia clínica.', 'Selecciona Programar sesiones.', 'Completa la programación y confirma.'], '/historias-clinicas', '¿Cómo programo sesiones?'),
  guide('historias.imprimir', 'historias', 'historias', 'Imprimir una historia', ['imprimir historia', 'descargar historia'], ['imprimir', 'historia'], 'Abre el detalle de la historia y utiliza la opción de impresión disponible.', ['Abre la historia.', 'Selecciona Imprimir.'], '/historias-clinicas', '¿Cómo imprimo una historia?'),

  guide('agenda.crear', 'agenda', 'agenda', 'Crear una cita', ['crear cita', 'agendar cita', 'nueva cita', 'reservar cita'], ['crear', 'agendar', 'cita'], 'La cita se registra desde el módulo Citas / Agenda.', ['Ingresa a Citas / Agenda.', 'Presiona Nueva cita.', 'Completa los datos solicitados.', 'Guarda la cita.'], '/citas', '¿Cómo creo una cita?'),
  guide('agenda.confirmar', 'agenda', 'agenda', 'Confirmar una cita', ['confirmar cita', 'cita confirmada'], ['confirmar', 'cita', 'estado'], 'Cambia el estado de la cita desde sus acciones disponibles.', ['Localiza la cita.', 'Abre sus acciones.', 'Selecciona el estado confirmado y guarda.'], '/citas', '¿Cómo confirmo una cita?'),
  guide('agenda.reprogramar', 'agenda', 'agenda', 'Reprogramar una cita', ['reprogramar cita', 'cambiar fecha cita', 'cambiar horario cita', 'mover cita'], ['reprogramar', 'mover', 'cita', 'horario'], 'Reprograma la cita desde la opción de edición.', ['Localiza la cita.', 'Abre Editar.', 'Cambia la fecha o el horario.', 'Guarda los cambios.'], '/citas', '¿Cómo reprogramo una cita?'),
  guide('agenda.cancelar', 'agenda', 'agenda', 'Cancelar una cita', ['cancelar cita', 'anular cita'], ['cancelar', 'cita', 'estado'], 'La cancelación se registra cambiando el estado desde las acciones de la cita.', ['Localiza la cita.', 'Abre sus acciones.', 'Selecciona el estado cancelado y confirma.'], '/citas', '¿Cómo cancelo una cita?'),
  guide('agenda.falta', 'agenda', 'agenda', 'Registrar una falta', ['registrar falta', 'paciente no asistio', 'falto a cita'], ['falta', 'asistio', 'cita'], 'Registra la inasistencia mediante el estado correspondiente de la cita.', ['Localiza la cita.', 'Abre sus acciones.', 'Selecciona el estado de inasistencia y confirma.'], '/citas', '¿Cómo registro una falta?'),
  guide('agenda.disponibilidad', 'agenda', 'agenda', 'Consultar disponibilidad', ['consultar disponibilidad', 'horarios libres', 'ver calendario'], ['disponibilidad', 'horario', 'calendario'], 'Usa la vista Calendario para revisar las citas registradas antes de elegir un horario.', ['Ingresa a Citas / Agenda.', 'Abre la pestaña Calendario.', 'Revisa el día y horario necesarios.'], '/citas', '¿Cómo consulto disponibilidad?'),

  guide('sesiones.crear', 'sesiones', 'sesiones', 'Registrar una sesión', ['registrar sesion', 'crear sesion', 'nueva sesion'], ['registrar', 'sesion', 'atencion'], 'La atención se registra desde el módulo Sesiones.', ['Ingresa a Sesiones.', 'Presiona Nueva sesión.', 'Completa la información clínica disponible.', 'Guarda la sesión.'], '/sesiones', '¿Cómo registro una sesión?'),
  guide('sesiones.editar', 'sesiones', 'sesiones', 'Editar una sesión', ['editar sesion', 'modificar sesion'], ['editar', 'sesion'], 'Abre la acción Editar del registro de sesión.', ['Localiza la sesión.', 'Selecciona Editar.', 'Actualiza la información y guarda.'], '/sesiones', '¿Cómo edito una sesión?'),
  guide('sesiones.evolucion', 'sesiones', 'sesiones', 'Registrar una evolución', ['registrar evolucion', 'evolucion de sesion'], ['evolucion', 'sesion', 'registrar'], 'Documenta la evolución dentro del formulario de la sesión correspondiente.', ['Abre o crea la sesión.', 'Completa el apartado de evolución.', 'Guarda el registro.'], '/sesiones', '¿Cómo registro una evolución?'),
  guide('sesiones.dolor', 'sesiones', 'sesiones', 'Registrar dolor antes y después', ['dolor antes despues', 'registrar dolor', 'escala dolor'], ['dolor', 'antes', 'despues'], 'Usa los campos de dolor antes y después disponibles en el formulario de sesión.', ['Abre la sesión.', 'Registra el dolor antes y después de la atención.', 'Guarda los cambios.'], '/sesiones', '¿Dónde registro el dolor?'),
  guide('sesiones.tecnicas', 'sesiones', 'sesiones', 'Registrar técnicas', ['registrar tecnicas', 'tecnicas sesion'], ['tecnicas', 'sesion'], 'Las técnicas aplicadas se documentan en el formulario de la sesión.', ['Abre la sesión.', 'Completa el apartado de técnicas.', 'Guarda el registro.'], '/sesiones', '¿Dónde registro las técnicas?'),
  guide('sesiones.medios', 'sesiones', 'sesiones', 'Registrar medios físicos', ['medios fisicos', 'registrar medios'], ['medios', 'fisicos', 'sesion'], 'Los medios físicos utilizados se documentan en el formulario de sesión.', ['Abre la sesión.', 'Completa el apartado de medios físicos.', 'Guarda el registro.'], '/sesiones', '¿Dónde registro medios físicos?'),
  guide('sesiones.farmacos', 'sesiones', 'sesiones', 'Registrar fármacos', ['farmacos sesion', 'registrar farmaco', 'medicamento sesion'], ['farmacos', 'medicamento', 'sesion'], 'Cuando corresponda, registra los fármacos en el apartado disponible del formulario de sesión.', ['Abre la sesión.', 'Completa la información de fármacos.', 'Guarda el registro.'], '/sesiones', '¿Dónde registro fármacos?'),

  guide('evoluciones.registrar', 'evoluciones', 'evolutivos', 'Registrar una evolución', ['crear evolutivo', 'registrar evolucion clinica'], ['crear', 'evolutivo', 'evolucion'], 'Inicia el registro desde Evolutivos clínicos y completa la información solicitada.', ['Ingresa a Evolutivos clínicos.', 'Inicia un nuevo registro.', 'Completa y guarda la evolución.'], '/evolutivos-clinicos', '¿Cómo registro una evolución?'),
  guide('evoluciones.consultar', 'evoluciones', 'evolutivos', 'Consultar evoluciones', ['consultar evoluciones', 'ver evolutivos'], ['consultar', 'evoluciones', 'evolutivos'], 'Usa el listado de Evolutivos clínicos para localizar y consultar los registros.', ['Ingresa a Evolutivos clínicos.', 'Busca el registro que necesitas.', 'Abre su detalle.'], '/evolutivos-clinicos', '¿Cómo consulto una evolución?'),

  guide('informes.crear', 'informes', 'informes', 'Crear un informe', ['crear informe', 'nuevo informe medico'], ['crear', 'informe'], 'El informe se crea desde Informes médicos.', ['Ingresa a Informes médicos.', 'Presiona Nuevo informe.', 'Completa el documento y guarda.'], '/informes-medicos', '¿Cómo creo un informe?'),
  guide('informes.editar', 'informes', 'informes', 'Editar un informe', ['editar informe', 'modificar informe'], ['editar', 'informe'], 'Usa la acción Editar del informe correspondiente.', ['Localiza el informe.', 'Selecciona Editar.', 'Guarda los cambios.'], '/informes-medicos', '¿Cómo edito un informe?'),
  guide('informes.imprimir', 'informes', 'informes', 'Imprimir un informe', ['imprimir informe'], ['imprimir', 'informe'], 'Abre el informe y usa la opción Imprimir.', ['Abre el informe.', 'Selecciona Imprimir.'], '/informes-medicos', '¿Cómo imprimo un informe?'),
  guide('informes.pdf', 'informes', 'informes', 'Descargar informe en PDF', ['descargar pdf informe', 'pdf informe'], ['descargar', 'pdf', 'informe'], 'Desde la vista del informe utiliza la opción de descarga en PDF.', ['Abre el informe.', 'Selecciona Descargar PDF.'], '/informes-medicos', '¿Cómo descargo el PDF?'),

  guide('documentos.consentimiento', 'consentimiento', 'documentosClinicos', 'Consentimiento informado', ['consentimiento informado', 'crear consentimiento'], ['consentimiento', 'documento'], 'Gestiona el documento desde Consentimiento informado.', ['Abre Documentos clínicos y selecciona Consentimiento informado.', 'Crea o abre el documento necesario.', 'Completa, guarda o imprime según corresponda.'], '/documentos/consentimiento-informado', '¿Cómo registro un consentimiento?'),
  guide('documentos.signos', 'signos-vitales', 'documentosClinicos', 'Registrar signos vitales', ['registrar signos vitales', 'signos vitales'], ['signos', 'vitales', 'registrar'], 'Gestiona el registro desde el documento Signos vitales.', ['Abre Documentos clínicos y selecciona Signos vitales.', 'Crea el documento.', 'Completa la información y guarda.'], '/documentos/signos-vitales', '¿Cómo registro signos vitales?'),
  guide('documentos.farmacos', 'farmacos', 'documentosClinicos', 'Administración de fármacos', ['administracion farmacos', 'documento farmacos'], ['administracion', 'farmacos', 'documento'], 'Gestiona este registro desde Administración de fármacos.', ['Abre Documentos clínicos y selecciona Administración de fármacos.', 'Crea o abre el documento.', 'Completa y guarda la información permitida.'], '/documentos/administracion-farmacos', '¿Cómo registro la administración de fármacos?'),

  guide('semanales.consultar', 'sesiones-semanales', 'sesionesSemanales', 'Consultar sesiones semanales', ['consultar sesiones semanales', 'ver semana'], ['consultar', 'sesiones', 'semana'], 'Usa los controles de Sesiones semanales para consultar el período necesario.', ['Ingresa a Sesiones semanales.', 'Selecciona el período disponible.', 'Consulta el resultado.'], '/sesiones-semanales', '¿Cómo consulto las sesiones?'),
  guide('semanales.recalcular', 'sesiones-semanales', 'sesionesSemanales', 'Recalcular sesiones semanales', ['recalcular sesiones', 'actualizar semana'], ['recalcular', 'sesiones', 'semana'], 'Utiliza la opción Recalcular para actualizar el resumen del período.', ['Selecciona el período.', 'Presiona Recalcular.', 'Revisa el resultado actualizado.'], '/sesiones-semanales', '¿Cómo recalculo la semana?'),
  guide('semanales.exportar', 'sesiones-semanales', 'sesionesSemanales', 'Exportar sesiones semanales', ['exportar sesiones', 'descargar excel semanal'], ['exportar', 'excel', 'sesiones'], 'Utiliza la opción de exportación; el archivo respetará la información permitida para tu rol.', ['Selecciona el período.', 'Presiona la opción de exportar.'], '/sesiones-semanales', '¿Cómo exporto la información?'),

  guide('planillas.crear', 'planillas-atencion', 'planillasAtencion', 'Crear planilla de atención', ['crear planilla atencion', 'nueva planilla'], ['crear', 'planilla', 'atencion'], 'Inicia una planilla desde Planillas de atención.', ['Ingresa a Planillas de atención.', 'Presiona la opción para crear una planilla.', 'Completa y guarda el documento.'], '/planillas-atencion', '¿Cómo creo una planilla?'),
  guide('planillas.editar', 'planillas-atencion', 'planillasAtencion', 'Editar planilla de atención', ['editar planilla atencion'], ['editar', 'planilla'], 'Usa la acción Editar de la planilla correspondiente.', ['Localiza la planilla.', 'Selecciona Editar.', 'Guarda los cambios.'], '/planillas-atencion', '¿Cómo edito una planilla?'),
  guide('planillas.pdf', 'planillas-atencion', 'planillasAtencion', 'Descargar planilla en PDF', ['descargar pdf planilla', 'pdf planilla'], ['descargar', 'pdf', 'planilla'], 'Abre la planilla y utiliza la opción de PDF disponible.', ['Abre la planilla.', 'Selecciona Descargar PDF.'], '/planillas-atencion', '¿Cómo descargo el PDF?'),

  guide('actividades.crear', 'actividades', 'actividadesPropias', 'Crear actividad', ['crear actividad', 'nueva tarea extra'], ['crear', 'actividad', 'tarea'], 'Registra una actividad propia desde Mis actividades.', ['Ingresa a Mis actividades.', 'Presiona Nueva tarea extra.', 'Completa y guarda la actividad.'], '/personal/actividades', '¿Cómo creo una actividad?'),
  guide('actividades.editar', 'actividades', 'actividadesPropias', 'Editar actividad propia', ['editar actividad', 'editar tarea'], ['editar', 'actividad', 'tarea'], 'Usa la acción Editar de una actividad propia.', ['Localiza tu actividad.', 'Selecciona Editar.', 'Guarda los cambios.'], '/personal/actividades', '¿Cómo edito una actividad?'),
  guide('actividades.estado', 'actividades', 'actividadesPropias', 'Cambiar estado de actividad', ['cambiar estado actividad', 'completar actividad'], ['estado', 'actividad', 'completar'], 'Actualiza el estado desde las acciones de tu actividad.', ['Localiza tu actividad.', 'Cambia su estado con la opción disponible.'], '/personal/actividades', '¿Cómo cambio el estado?'),
  guide('actividades.eliminar', 'actividades', 'actividadesPropias', 'Eliminar actividad propia', ['eliminar actividad propia', 'borrar tarea'], ['eliminar', 'actividad', 'propia'], 'Puedes eliminar únicamente una actividad propia mediante su acción disponible.', ['Localiza tu actividad.', 'Selecciona Eliminar.', 'Confirma la operación.'], '/personal/actividades', '¿Cómo elimino una actividad propia?'),

  guide('notificaciones.consultar', 'notificaciones', null, 'Consultar notificaciones', ['ver notificaciones', 'consultar notificaciones'], ['ver', 'notificaciones', 'avisos'], 'Abre Notificaciones desde la barra superior para consultar tus avisos.', ['Selecciona el acceso de Notificaciones.', 'Revisa el listado.'], '/notificaciones', '¿Cómo veo mis notificaciones?'),
  guide('notificaciones.leer', 'notificaciones', null, 'Marcar notificación como leída', ['marcar notificacion leida', 'leer notificacion'], ['marcar', 'leida', 'notificacion'], 'Usa la acción de lectura disponible en la notificación.', ['Localiza la notificación.', 'Ábrela o usa Marcar como leída.'], '/notificaciones', '¿Cómo marco una notificación como leída?'),

  guide('whatsapp.ver', 'recepcion-whatsapp', 'recepcionWhatsapp', 'Ver solicitudes de WhatsApp', ['ver solicitudes whatsapp', 'bandeja whatsapp'], ['solicitudes', 'whatsapp', 'bandeja'], 'Las solicitudes se consultan en Recepción WhatsApp.', ['Ingresa a Recepción WhatsApp.', 'Revisa la bandeja y sus estados.'], '/whatsapp/recepcion', '¿Cómo veo las solicitudes?'),
  guide('whatsapp.tomar', 'recepcion-whatsapp', 'recepcionWhatsapp', 'Tomar una solicitud', ['tomar solicitud whatsapp', 'asignarme solicitud'], ['tomar', 'solicitud', 'whatsapp'], 'Usa la acción Tomar solicitud en el elemento correspondiente.', ['Abre la solicitud.', 'Selecciona Tomar solicitud.'], '/whatsapp/recepcion', '¿Cómo tomo una solicitud?'),
  guide('whatsapp.responder', 'recepcion-whatsapp', 'recepcionWhatsapp', 'Responder una solicitud', ['responder solicitud whatsapp', 'responder whatsapp'], ['responder', 'solicitud', 'whatsapp'], 'Abre la solicitud tomada y utiliza el espacio de respuesta disponible.', ['Abre la solicitud.', 'Escribe la respuesta.', 'Envía la respuesta.'], '/whatsapp/recepcion', '¿Cómo respondo una solicitud?'),
  guide('whatsapp.resolver', 'recepcion-whatsapp', 'recepcionWhatsapp', 'Resolver una solicitud', ['resolver solicitud whatsapp', 'cerrar solicitud whatsapp'], ['resolver', 'cerrar', 'solicitud'], 'Cuando la atención termine, utiliza la acción Resolver en la solicitud.', ['Abre la solicitud.', 'Selecciona Resolver y confirma.'], '/whatsapp/recepcion', '¿Cómo resuelvo una solicitud?'),

  guide('blog.crear', 'blog', 'blogAdministracion', 'Crear borrador del blog', ['crear borrador blog', 'nuevo articulo'], ['crear', 'borrador', 'blog', 'articulo'], 'Inicia una publicación desde el listado del Blog.', ['Ingresa a Blog.', 'Selecciona Nuevo artículo.', 'Completa el contenido y guarda el borrador.'], '/blog/nuevo', '¿Cómo creo un borrador?'),
  guide('blog.editar', 'blog', 'blogAdministracion', 'Editar artículo propio', ['editar articulo propio', 'editar blog'], ['editar', 'articulo', 'blog', 'propio'], 'Usa la acción Editar de uno de tus artículos.', ['Localiza tu artículo.', 'Selecciona Editar.', 'Guarda los cambios.'], '/blog', '¿Cómo edito mi artículo?'),

  guide('pacientes.documento-duplicado', 'pacientes', 'pacientes', 'Validación de documento duplicado', ['documento duplicado', 'paciente duplicado', 'validar documento'], ['documento', 'duplicado', 'paciente'], 'Al registrar o editar, el sistema comprueba si el tipo y número de documento ya pertenecen a un paciente activo o inactivo.', [], '/pacientes', null, BOTH, { tips: ['Busca primero por documento de identidad antes de crear un registro nuevo.'] }),
  guide('historias.campos', 'historias', 'historias', 'Contenido de la historia clínica', ['que debo completar historia', 'campos historia clinica', 'plan de tratamiento'], ['historia', 'diagnostico', 'motivo', 'antecedentes', 'examen', 'plan'], 'La historia organiza el motivo de consulta, enfermedad actual, antecedentes, examen kinésico, evaluación y plan de tratamiento disponibles en el formulario. Su función es documentar el uso del sistema; el asistente no realiza diagnósticos ni recomienda tratamientos.', [], '/historias-clinicas', '¿Qué debo completar aquí?'),
  guide('agenda.estados', 'agenda', 'agenda', 'Estados de las citas', ['estados cita', 'que significan los estados', 'estado de cita'], ['estados', 'cita', 'pendiente', 'programada', 'confirmada'], 'Los estados reales son Pendiente, Programada, Confirmada, Atendida, Cancelada, Reprogramada, No asistio y Falto. Indican la situación operativa de la cita.', [], '/citas', '¿Qué significan los estados?'),
  guide('agenda.confirmada-significado', 'agenda', 'agenda', 'Cita confirmada', ['que significa confirmada', 'cita confirmada significado'], ['confirmada', 'cita', 'estado'], 'Confirmada indica que la cita programada fue confirmada y continúa prevista para su fecha y horario.', [], '/citas', '¿Qué significa Confirmada?'),
  guide('agenda.falta-significado', 'agenda', 'agenda', 'Falta o inasistencia', ['que significa falta', 'que significa falto', 'no asistio significado'], ['falta', 'falto', 'inasistencia'], 'Falto o No asistio registra que la persona no asistió a la cita. Esa situación no requiere una evolución clínica de sesión.', [], '/citas', null),
  guide('agenda.cita-sesion', 'agenda', 'agenda', 'Diferencia entre cita y sesión', ['diferencia cita sesion', 'cita o sesion'], ['diferencia', 'cita', 'sesion'], 'La cita organiza la fecha y el horario. La sesión clínica registra la asistencia y la atención efectivamente realizada.', [], '/citas', null),
  guide('acciones.reprogramar', 'agenda', 'agenda', 'Acción Reprogramar', ['que hace reprogramar', 'para que sirve reprogramar'], ['reprogramar', 'boton'], 'Reprogramar permite cambiar la fecha o el horario de una cita que todavía no está atendida o cancelada.', [], '/citas', null),
  guide('acciones.anular-historia', 'historias', 'historias', 'Acción Anular historia', ['que significa anular', 'que hace anular historia'], ['anular', 'historia'], 'Anular retira la historia del trabajo activo, pero la conserva en el historial del sistema.', [], '/historias-clinicas', null, ADMIN, { warnings: ['Esta acción está disponible únicamente para ADMIN.'] }),
  guide('acciones.restaurar-historia', 'historias', 'historias', 'Acción Restaurar historia', ['que hace restaurar', 'restaurar historia'], ['restaurar', 'historia'], 'Restaurar vuelve a habilitar una historia previamente anulada.', [], '/historias-clinicas', null, ADMIN, { warnings: ['Esta acción está disponible únicamente para ADMIN.'] }),
  guide('acciones.recalcular', 'sesiones-semanales', 'sesionesSemanales', 'Acción Recalcular', ['que hace recalcular', 'para que sirve recalcular'], ['recalcular', 'semana'], 'Recalcular actualiza el resumen semanal usando los registros disponibles del período seleccionado.', [], '/sesiones-semanales', null),
  guide('acciones.pdf', 'informes', 'informes', 'Acción Descargar PDF', ['que hace descargar pdf', 'para que sirve pdf'], ['descargar', 'pdf'], 'Descargar PDF genera una copia del documento para guardarla o compartirla fuera de la vista de edición.', [], '/informes-medicos', null),
  guide('whatsapp.estados', 'recepcion-whatsapp', 'recepcionWhatsapp', 'Estados de solicitudes WhatsApp', ['estados whatsapp', 'estado solicitud whatsapp'], ['pendiente', 'en atencion', 'resuelta', 'cerrada', 'cancelada'], 'Las solicitudes usan los estados Pendiente, En atención, Resuelta, Cerrada y Cancelada. El estado determina si puede tomarse, recibir observaciones, resolverse o cerrarse.', [], '/whatsapp/recepcion', null),
  guide('actividades.estados', 'actividades', 'actividadesPropias', 'Estados de actividades', ['estados actividad', 'estado tarea'], ['pendiente', 'en progreso', 'completada', 'cancelada'], 'Las tareas extra pueden estar Pendientes, En progreso, Completadas o Canceladas.', [], '/personal/actividades', null),

  guide('admin.finanzas', 'finanzas', 'finanzas', 'Control financiero', ['ver finanzas', 'control financiero', 'pagos deudores arqueos'], ['finanzas', 'pagos', 'deudores', 'arqueos'], 'El Control financiero centraliza planillas de pagos, deudas, recibos, comprobantes y arqueos.', ['Abre Control financiero desde el menú.', 'Selecciona la vista o acción financiera necesaria.'], '/control-financiero/planilla-pagos', '¿Cómo uso Finanzas?', ADMIN),
  guide('admin.usuarios', 'usuarios', 'usuarios', 'Administrar usuarios', ['administrar usuarios', 'crear usuario', 'gestionar cuentas'], ['usuarios', 'cuentas', 'administrar'], 'Usuarios permite administrar las cuentas habilitadas en el sistema.', ['Ingresa a Usuarios.', 'Usa las acciones disponibles para la cuenta necesaria.'], '/usuarios', '¿Cómo administro usuarios?', ADMIN),
  guide('admin.personal', 'usuarios', 'personalAdministracion', 'Administrar personal', ['administrar personal', 'gestion de personal'], ['personal', 'administrar', 'empleados'], 'La administración de personal está integrada en el área de Usuarios y personal.', ['Ingresa a Usuarios y personal.', 'Selecciona la acción administrativa necesaria.'], '/usuarios', '¿Cómo administro el personal?', ADMIN),
  guide('admin.sueldos', 'sueldos', 'sueldos', 'Planillas de sueldos', ['planillas de sueldos', 'ver sueldos', 'nomina salarial'], ['planillas', 'sueldos', 'salarios'], 'Las planillas laborales y salariales se gestionan en Planillas de sueldos.', ['Abre Personal en el menú.', 'Ingresa a Planillas de sueldos.', 'Selecciona la planilla que deseas consultar o gestionar.'], '/personal/planilla', '¿Cómo veo planillas de sueldos?', ADMIN),
  guide('admin.roles', 'roles-permisos', 'rolesPermisos', 'Roles y permisos', ['roles y permisos', 'ver permisos', 'cambiar roles'], ['roles', 'permisos', 'acceso'], 'La pantalla Roles y permisos presenta la matriz de acceso aplicada por el sistema.', ['Ingresa a Roles y permisos.', 'Consulta la política del módulo requerido.'], '/roles-permisos', '¿Dónde veo los permisos?', ADMIN),
  guide('admin.monitoring', 'monitoreo-whatsapp', 'monitoreoWhatsapp', 'Monitoreo WhatsApp', ['monitoreo whatsapp', 'estado whatsapp'], ['monitoreo', 'whatsapp', 'estado'], 'El monitoreo muestra el estado operativo de la integración de WhatsApp.', ['Ingresa a Monitoreo WhatsApp.', 'Revisa los indicadores disponibles.'], '/whatsapp/monitoring', '¿Cómo veo el monitoreo de WhatsApp?', ADMIN),
  guide('admin.categorias', 'categorias-blog', 'blogCategorias', 'Categorías del blog', ['categorias blog', 'administrar categorias'], ['categorias', 'blog', 'administrar'], 'Las categorías de publicaciones se administran desde Categorías del blog.', ['Ingresa a Blog.', 'Abre Categorías.', 'Usa las acciones disponibles.'], '/blog/categorias', '¿Cómo administro categorías?', ADMIN)
]);
