import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowDownCircle, ArrowUpCircle, Eye, Landmark, Plus, RefreshCw, RotateCcw, WalletCards } from 'lucide-react';
import ActionButton from '../../components/common/ActionButton';
import Button from '../../components/common/Button';
import Input from '../../components/common/Input';
import Loader from '../../components/common/Loader';
import Modal from '../../components/common/Modal';
import Table from '../../components/common/Table';
import { annulMovimientoCaja, createMovimientoCaja, getMovimientosCaja, getResumenMovimientosCaja } from '../../services/movimientoCajaService';
import { boliviaDate } from '../../utils/boliviaDateTime';
import { formatDate } from '../../utils/formatDate';

const TYPES = [
  ['INGRESO_EXTRAORDINARIO', 'Ingreso extraordinario'], ['EGRESO', 'Egreso'], ['APORTE_CAJA', 'Aporte de caja'],
  ['RETIRO_CAJA', 'Retiro de caja'], ['AJUSTE_POSITIVO', 'Ajuste positivo'], ['AJUSTE_NEGATIVO', 'Ajuste negativo']
];
const CATEGORIES = ['MATERIAL_MEDICO','INSUMOS','LIMPIEZA','MANTENIMIENTO','SERVICIOS','TRANSPORTE','PAPELERIA','PERSONAL','OTROS'];
const METHODS = ['Efectivo','QR','Transferencia','Tarjeta','Otro'];
const typeName = Object.fromEntries(TYPES);
const incoming = new Set(['INGRESO_EXTRAORDINARIO','APORTE_CAJA','AJUSTE_POSITIVO']);
const cashOnly = new Set(['APORTE_CAJA','RETIRO_CAJA','AJUSTE_POSITIVO','AJUSTE_NEGATIVO']);
const money = (value) => `Bs ${Number(value || 0).toLocaleString('es-BO', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const iso = (date) => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const rangeFor = (mode, anchor) => { const d=new Date(`${anchor}T12:00:00`); if(mode==='hoy')return{desde:anchor,hasta:anchor}; if(mode==='semana'){const s=new Date(d);s.setDate(d.getDate()-((d.getDay()+6)%7));const e=new Date(s);e.setDate(s.getDate()+6);return{desde:iso(s),hasta:iso(e)}} if(mode==='mes')return{desde:iso(new Date(d.getFullYear(),d.getMonth(),1)),hasta:iso(new Date(d.getFullYear(),d.getMonth()+1,0))}; return null; };
const emptyForm = (date) => ({ tipo_movimiento:'INGRESO_EXTRAORDINARIO',categoria:'',concepto:'',monto:'',metodo:'Efectivo',fecha:date,hora:'',descripcion:'',motivo:'',comprobante:'' });

function Card({ label, value, icon: Icon, tone }) { return <article className={`rounded-xl border p-4 ${tone}`}><div className="flex items-center justify-between"><span className="text-xs font-black uppercase">{label}</span><Icon size={19}/></div><strong className="mt-3 block text-2xl text-slate-900">{value}</strong></article>; }

export default function MovimientosCaja() {
  const today=boliviaDate(); const [mode,setMode]=useState('hoy'); const [anchor,setAnchor]=useState(today); const [custom,setCustom]=useState({desde:today,hasta:today});
  const [filters,setFilters]=useState({tipo:'Todos',metodo:'Todos',estado:'ACTIVO',categoria:'Todas',texto:''}); const [data,setData]=useState({items:[],total:0,page:1,pages:1});
  const [summary,setSummary]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [form,setForm]=useState(emptyForm(today));
  const [showForm,setShowForm]=useState(false); const [detail,setDetail]=useState(null); const [annul,setAnnul]=useState(null); const [annulReason,setAnnulReason]=useState(''); const [saving,setSaving]=useState(false);
  const range=useMemo(()=>mode==='personalizado'?custom:rangeFor(mode,anchor),[mode,anchor,custom]);
  const load=useCallback(async()=>{if(!range||range.desde>range.hasta)return;setLoading(true);setError('');try{const params={...range,...filters,page:1,limit:100};const [list,res]=await Promise.all([getMovimientosCaja(params),getResumenMovimientosCaja(range)]);setData(list);setSummary(res);}catch(e){setError(e.message);}finally{setLoading(false);}},[filters,range]);
  useEffect(()=>{load();},[load]);
  const submit=async(e)=>{e.preventDefault();setSaving(true);try{await createMovimientoCaja({...form,categoria:form.tipo_movimiento==='EGRESO'?form.categoria:null,motivo:form.motivo||null,hora:form.hora||undefined});setShowForm(false);setForm(emptyForm(today));await load();}finally{setSaving(false);}};
  const confirmAnnul=async()=>{if(!annulReason.trim())return;setSaving(true);try{await annulMovimientoCaja(annul.id,annulReason);setAnnul(null);setAnnulReason('');await load();}finally{setSaving(false);}};
  const options=(rows,all)=>[{value:all,label:all},...rows.map(([value,label])=>({value,label}))];
  return <section className="grid gap-5">{loading&&<Loader/>}
    <header className="rounded-xl border border-teal-100 bg-gradient-to-r from-teal-50 via-white to-sky-50 p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase text-teal-700">Control financiero</p><h1 className="mt-1 text-3xl font-black">Ingresos y egresos</h1><p className="mt-1 text-sm text-slate-600">Control de entradas, salidas y movimientos de caja.</p></div><div className="flex gap-2"><Button variant="secondary" onClick={load}><RefreshCw size={16}/>Actualizar</Button><Button onClick={()=>setShowForm(true)}><Plus size={16}/>Nuevo movimiento</Button></div></div>
      <div className="mt-4 rounded-xl border bg-white/80 p-3"><div className="flex flex-wrap gap-2">{[['hoy','Hoy'],['semana','Semana'],['mes','Mes'],['personalizado','Personalizado']].map(([key,label])=><button key={key} onClick={()=>setMode(key)} className={`min-h-10 rounded-lg px-4 text-sm font-black ${mode===key?'bg-teal-600 text-white':'bg-slate-50 text-slate-600'}`}>{label}</button>)}</div><div className="mt-3 flex flex-wrap gap-3">{mode==='personalizado'?<><Input compact label="Desde" type="date" value={custom.desde} onChange={e=>setCustom({...custom,desde:e.target.value})}/><Input compact label="Hasta" type="date" value={custom.hasta} onChange={e=>setCustom({...custom,hasta:e.target.value})}/></>:<Input compact label="Fecha de referencia" type="date" value={anchor} onChange={e=>setAnchor(e.target.value)}/>}</div></div>
    </header>
    {error&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>}
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><Card label="Ingresos operativos" value={money(summary?.ingresos_operativos)} icon={ArrowUpCircle} tone="border-emerald-100 bg-emerald-50 text-emerald-700"/><Card label="Egresos operativos" value={money(summary?.egresos)} icon={ArrowDownCircle} tone="border-red-100 bg-red-50 text-red-700"/><Card label="Aportes" value={money(summary?.aportes)} icon={Plus} tone="border-sky-100 bg-sky-50 text-sky-700"/><Card label="Retiros manuales" value={money(summary?.retiros)} icon={RotateCcw} tone="border-amber-100 bg-amber-50 text-amber-700"/><Card label="Efectivo esperado en caja" value={summary?.detalle_saldo?.apertura_pendiente?'Pendiente de definir apertura':money(summary?.saldo_caja)} icon={WalletCards} tone="border-violet-100 bg-violet-50 text-violet-700"/></div>
    <div className="rounded-xl border border-sky-100 bg-sky-50/70 px-4 py-3 text-sm text-slate-700"><b>Movimientos manuales de caja.</b> Esta tabla muestra únicamente movimientos manuales de caja. Los cobros de pacientes se registran en Planilla de pagos y se incluyen automáticamente en los ingresos operativos.<div className="mt-1 flex flex-wrap gap-x-4 text-xs text-slate-600"><span>Cobros de pacientes: <b>{money(summary?.pagos_pacientes)}</b></span><span>Ingresos extraordinarios: <b>{money(summary?.ingresos_extraordinarios)}</b></span></div></div>
    <section className="panel grid gap-3"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Input compact label="Tipo" options={options(TYPES,'Todos')} value={filters.tipo} onChange={e=>setFilters({...filters,tipo:e.target.value})}/><Input compact label="Método" options={options(METHODS.map(x=>[x,x]),'Todos')} value={filters.metodo} onChange={e=>setFilters({...filters,metodo:e.target.value})}/><Input compact label="Estado" options={options([['ACTIVO','Activo'],['ANULADO','Anulado']],'Todos')} value={filters.estado} onChange={e=>setFilters({...filters,estado:e.target.value})}/><Input compact label="Categoría" options={options(CATEGORIES.map(x=>[x,x.replaceAll('_',' ')]),'Todas')} value={filters.categoria} onChange={e=>setFilters({...filters,categoria:e.target.value})}/><Input compact label="Buscar" value={filters.texto} onChange={e=>setFilters({...filters,texto:e.target.value})}/></div>
      <Table paginate={false} columns={['Fecha','Tipo','Concepto','Método','Monto','Responsable','Estado','Acciones']} rows={data.items.map(x=>[`${formatDate(x.fecha)} ${String(x.hora||'').slice(0,5)}`,typeName[x.tipo_movimiento],<span>{x.concepto}{x.advertencia_clasificacion&&<small className="mt-1 block font-bold text-amber-700">{x.advertencia_clasificacion}</small>}</span>,x.metodo,<b className={incoming.has(x.tipo_movimiento)?'text-emerald-700':'text-red-700'}>{incoming.has(x.tipo_movimiento)?'+':'-'} {money(x.monto)}</b>,x.registradoPor?.nombre||'—',x.estado,<div className="flex gap-1"><ActionButton label="Ver detalle" icon={Eye} tone="view" onClick={()=>setDetail(x)}/>{x.estado==='ACTIVO'&&<ActionButton label="Anular" icon={RotateCcw} tone="danger" onClick={()=>setAnnul(x)}/>}</div>])} empty="No existen movimientos manuales de caja para los filtros seleccionados."/>
      {!loading && data.items.length === 0 && <p className="text-center text-xs text-slate-500">Los cobros de pacientes pueden consultarse desde Planilla de pagos.</p>}
    </section>
    <Modal open={showForm} title="Nuevo movimiento" subtitle="Registra una entrada o salida adicional de caja." onClose={()=>setShowForm(false)} size="compact"><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Input label="Tipo de movimiento *" options={TYPES.map(([value,label])=>({value,label}))} value={form.tipo_movimiento} onChange={e=>setForm({...form,tipo_movimiento:e.target.value,categoria:'',metodo:cashOnly.has(e.target.value)?'Efectivo':form.metodo})}/>{form.tipo_movimiento==='EGRESO'&&<Input label="Categoría *" options={[{value:'',label:'Seleccione'},...CATEGORIES.map(x=>({value:x,label:x.replaceAll('_',' ')}))]} value={form.categoria} onChange={e=>setForm({...form,categoria:e.target.value})} required/>}<Input label="Concepto *" value={form.concepto} onChange={e=>setForm({...form,concepto:e.target.value})} required/><Input label="Monto *" type="number" min="0.01" step="0.01" value={form.monto} onChange={e=>setForm({...form,monto:e.target.value})} required/><Input label="Método *" options={(cashOnly.has(form.tipo_movimiento)?['Efectivo']:METHODS).map(x=>({value:x,label:x}))} value={form.metodo} onChange={e=>setForm({...form,metodo:e.target.value})} disabled={cashOnly.has(form.tipo_movimiento)}/><Input label="Fecha *" type="date" value={form.fecha} onChange={e=>setForm({...form,fecha:e.target.value})} required/><Input label="Hora" type="time" value={form.hora} onChange={e=>setForm({...form,hora:e.target.value})}/><Input label="Comprobante" value={form.comprobante} onChange={e=>setForm({...form,comprobante:e.target.value})}/><Input className="sm:col-span-2" label="Descripción" multiline value={form.descripcion} onChange={e=>setForm({...form,descripcion:e.target.value})}/>{(['AJUSTE_POSITIVO','AJUSTE_NEGATIVO','RETIRO_CAJA','APORTE_CAJA'].includes(form.tipo_movimiento))&&<Input className="sm:col-span-2" label="Motivo / origen / destino *" multiline value={form.motivo} onChange={e=>setForm({...form,motivo:e.target.value})} required={form.tipo_movimiento.startsWith('AJUSTE_')}/>}<div className="flex justify-end gap-2 sm:col-span-2"><Button variant="secondary" onClick={()=>setShowForm(false)}>Cancelar</Button><Button type="submit" disabled={saving}>{saving?'Guardando…':'Guardar movimiento'}</Button></div></form></Modal>
    <Modal open={Boolean(detail)} title="Detalle del movimiento" onClose={()=>setDetail(null)}>{detail&&<div className="grid gap-2 sm:grid-cols-2">{[['Tipo',typeName[detail.tipo_movimiento]],['Categoría',detail.categoria],['Concepto',detail.concepto],['Descripción',detail.descripcion],['Monto',money(detail.monto)],['Método',detail.metodo],['Fecha',formatDate(detail.fecha)],['Hora',String(detail.hora||'').slice(0,5)],['Responsable',detail.registradoPor?.nombre],['Estado',detail.estado],['Arqueo',detail.arqueo?.numero_arqueo],['Motivo',detail.motivo],['Motivo anulación',detail.motivo_anulacion]].filter(([,v])=>v).map(([k,v])=><div key={k} className="rounded-lg border bg-slate-50 p-3"><span className="text-xs font-black uppercase text-slate-500">{k}</span><b className="block">{v}</b></div>)}</div>}</Modal>
    <Modal open={Boolean(annul)} title="Anular movimiento" subtitle="El registro permanecerá en el historial." onClose={()=>setAnnul(null)} size="sm"><div className="grid gap-4"><Input label="Motivo de anulación *" multiline value={annulReason} onChange={e=>setAnnulReason(e.target.value)}/><div className="flex justify-end gap-2"><Button variant="secondary" onClick={()=>setAnnul(null)}>Cancelar</Button><Button variant="danger" disabled={saving||!annulReason.trim()} onClick={confirmAnnul}>Confirmar anulación</Button></div></div></Modal>
  </section>;
}
