import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Activity, AlertTriangle, Banknote, CalendarCheck, CalendarDays, CheckCircle2, ClipboardList,
  Download, Eye, FileSpreadsheet, FileText, HeartPulse, History, Pill, Plus, RefreshCw,
  Search, Stethoscope, UserRound, Users, WalletCards, XCircle
} from 'lucide-react';
import Swal from 'sweetalert2';
import Button from '../../components/common/Button';
import ActionButton from '../../components/common/ActionButton';
import Input from '../../components/common/Input';
import Loader from '../../components/common/Loader';
import Modal from '../../components/common/Modal';
import Table from '../../components/common/Table';
import { getPacientes } from '../../services/pacienteService';
import { getProfesionalesActivos } from '../../services/usuarioService';
import { createObservacionDiaria, getResumenDiario } from '../../services/resumenDiarioService';

const today = () => new Date().toLocaleDateString('en-CA', { timeZone: 'America/La_Paz' });
const formatDate = (value) => value ? new Date(`${value}T12:00:00`).toLocaleDateString('es-BO') : 'Sin fecha';
const money = (value) => `${Number(value || 0).toLocaleString('es-BO', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} Bs`;
const pain = (value) => value === null || value === undefined || value === '' ? 'Sin registrar' : `${value}/10`;
const tabs = [
  ['resumen','Resumen'],['atenciones','Atenciones'],['pagos','Pagos'],['deudas','Deudas'],
  ['evolutivos','Evolutivos'],['farmacos','Fármacos'],['personal','Personal'],['observaciones','Observaciones']
];
const blankObservation = { categoria: 'Observaciones clínicas', hora: new Date().toTimeString().slice(0,5), descripcion: '', paciente_id: '', responsable_id: '', estado: 'Pendiente' };

function Metric({ label, value, icon: Icon, tone = 'teal' }) {
  const styles={teal:'border-teal-100 bg-teal-50 text-teal-700',green:'border-emerald-100 bg-emerald-50 text-emerald-700',red:'border-red-100 bg-red-50 text-red-700',amber:'border-amber-100 bg-amber-50 text-amber-700',violet:'border-violet-100 bg-violet-50 text-violet-700',blue:'border-sky-100 bg-sky-50 text-sky-700'};
  return <article className={`rounded-xl border p-3 ${styles[tone]}`}><div className="flex items-center justify-between gap-2"><span className="text-[10px] font-black uppercase tracking-wide">{label}</span><Icon size={17}/></div><strong className="mt-2 block text-xl text-slate-900">{value}</strong></article>;
}

function DataView({ rows, columns, empty, actions }) {
  return <>{rows.length?<><div className="hidden md:block"><Table columns={[...columns.map(c=>c.label),...(actions?['Acciones']:[])]} rows={rows.map(row=>[...columns.map(c=>c.render?c.render(row):row[c.key]??'Sin registrar'),...(actions?[actions(row)]:[])])}/></div><div className="grid gap-3 md:hidden">{rows.map((row,index)=><article key={row.id||index} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid grid-cols-2 gap-3">{columns.map(c=><div key={c.key} className={c.wide?'col-span-2':''}><span className="block text-[10px] font-black uppercase text-slate-400">{c.label}</span><div className="mt-0.5 break-words text-sm font-semibold text-slate-700">{c.render?c.render(row):row[c.key]??'Sin registrar'}</div></div>)}</div>{actions&&<div className="mt-3 flex justify-end gap-2 border-t pt-3">{actions(row)}</div>}</article>)}</div></>:<div className="empty-state py-12">{empty}</div>}</>;
}

function SearchBar({ value, onChange, placeholder='Buscar paciente, historia o contenido...' }) { return <label className="flex min-h-10 min-w-0 items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 shadow-sm focus-within:border-teal-600"><Search size={17} className="shrink-0 text-slate-400"/><input value={value} onChange={e=>onChange(e.target.value)} className="min-w-0 flex-1 border-0 bg-transparent p-0 text-sm focus:ring-0" placeholder={placeholder}/></label>; }

function ObservationForm({ fecha, patients, professionals, onClose, onSaved }) {
  const [form,setForm]=useState({...blankObservation,fecha,responsable_id:professionals[0]?.id||''}); const set=(k,v)=>setForm(old=>({...old,[k]:v}));
  const submit=async(e)=>{e.preventDefault();try{await createObservacionDiaria(form);await onSaved();onClose();}catch(error){Swal.fire({icon:'error',title:'No se pudo registrar la observación',text:error.message,confirmButtonColor:'#0F766E'});}};
  return <form onSubmit={submit} className="grid gap-3"><div className="grid gap-3 sm:grid-cols-2"><Input label="Categoría" value={form.categoria} onChange={e=>set('categoria',e.target.value)} options={['Pacientes que faltaron','Observaciones clínicas','Problemas de pago','Incidencias administrativas','Problemas con equipos','Tareas pendientes','Otras observaciones'].map(v=>({value:v,label:v}))}/><Input label="Hora" type="time" value={form.hora} onChange={e=>set('hora',e.target.value)} required/><Input label="Paciente relacionado (opcional)" value={form.paciente_id} onChange={e=>set('paciente_id',e.target.value)} options={[{value:'',label:'Sin paciente relacionado'},...patients.map(p=>({value:p.id,label:`${p.nombres} ${p.apellidos}`}))]}/><Input label="Personal responsable" value={form.responsable_id} onChange={e=>set('responsable_id',e.target.value)} options={professionals.map(p=>({value:p.id,label:p.nombre||p.usuario}))} required/><Input label="Estado" value={form.estado} onChange={e=>set('estado',e.target.value)} options={[{value:'Pendiente',label:'Pendiente'},{value:'Resuelto',label:'Resuelto'}]} className="sm:col-span-2"/><Input label="Descripción" multiline value={form.descripcion} onChange={e=>set('descripcion',e.target.value)} className="sm:col-span-2" required/></div><div className="flex justify-end gap-2 border-t pt-3"><Button variant="secondary" onClick={onClose}>Cancelar</Button><Button type="submit">Guardar observación</Button></div></form>;
}

function ResumenDiario({ initialTab = 'resumen' }) {
  const navigate=useNavigate(); const [fecha,setFecha]=useState(today()); const [tab,setTab]=useState(initialTab); const [cache,setCache]=useState({}); const [loading,setLoading]=useState(false); const [query,setQuery]=useState(''); const [showObservation,setShowObservation]=useState(false); const [patients,setPatients]=useState([]); const [professionals,setProfessionals]=useState([]); const [staffDetail,setStaffDetail]=useState(null);
  const current=cache[tab]||{}; const indicators=current.indicadores||cache.resumen?.indicadores||{}; const counts=current.contadores||cache.resumen?.contadores||{};
  const load=async(section=tab,force=false)=>{if(cache[section]&&!force)return;setLoading(true);try{const result=await getResumenDiario(fecha,section);setCache(old=>({...old,[section]:result}));}catch(error){Swal.fire({icon:'error',title:'No se pudo cargar el resumen diario',text:error.message,confirmButtonColor:'#0F766E'});}finally{setLoading(false);}};
  useEffect(()=>{setCache({});setQuery('');getResumenDiario(fecha,tab).then(result=>setCache({[tab]:result})).catch(()=>{});},[fecha]);
  useEffect(()=>{load(tab);},[tab]);
  useEffect(()=>{Promise.all([getPacientes(),getProfesionalesActivos()]).then(([p,u])=>{setPatients(p.filter(x=>x.estado!==false));setProfessionals(u);}).catch(()=>{});},[]);
  const rows=useMemo(()=>{const source=current[tab]||[];if(!Array.isArray(source)||!query.trim())return source;const q=query.toLowerCase();return source.filter(item=>Object.values(item).filter(v=>typeof v==='string'||typeof v==='number').join(' ').toLowerCase().includes(q));},[current,tab,query]);
  const changeDate=(value)=>{if(value)setFecha(value);};
  const exportExcel=async()=>{const all=await getResumenDiario(fecha,'todo');const ExcelJS=(await import('exceljs')).default;const wb=new ExcelJS.Workbook();const add=(title,data)=>{const sheet=wb.addWorksheet(title);if(!data.length){sheet.addRow(['Sin registros']);return;}const keys=Object.keys(data[0]).filter(k=>!['id','paciente_id','historia_id','concepto_id','actividades'].includes(k));sheet.addRow(keys.map(k=>k.replaceAll('_',' ').toUpperCase()));data.forEach(row=>sheet.addRow(keys.map(k=>row[k]??'')));sheet.getRow(1).font={bold:true,color:{argb:'FFFFFFFF'}};sheet.getRow(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF0F766E'}};sheet.views=[{state:'frozen',ySplit:1}];sheet.autoFilter={from:{row:1,column:1},to:{row:Math.max(data.length+1,1),column:keys.length}};sheet.columns.forEach(c=>c.width=20);};add('Resumen',[all.indicators]);add('Atenciones',all.attentions);add('Pagos',all.payments);add('Deudas',all.debts);add('Evolutivos',all.evolutions);add('Fármacos',all.drugs);add('Personal',all.personnel);add('Observaciones',all.observations);const blob=new Blob([await wb.xlsx.writeBuffer()],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Resumen_Diario_${fecha.split('-').reverse().join('-')}.xlsx`;a.click();URL.revokeObjectURL(a.href);};
  const downloadPdf=async()=>{const all=await getResumenDiario(fecha,'todo');const {jsPDF}=await import('jspdf');const pdf=new jsPDF();pdf.setTextColor(15,118,110);pdf.setFontSize(18);pdf.text('PHYSIO ACTIVE',15,18);pdf.setTextColor(30,41,59);pdf.setFontSize(15);pdf.text(`Resumen diario — ${formatDate(fecha)}`,15,29);pdf.setFontSize(10);let y=40;Object.entries(all.indicators).forEach(([k,v])=>{pdf.text(`${k.replaceAll('_',' ')}: ${k.includes('total_')?money(v):v}`,15,y);y+=6;if(y>275){pdf.addPage();y=18;}});pdf.setFontSize(12);pdf.text('Alertas y observaciones importantes',15,y+5);y+=12;(all.alerts||[]).forEach(a=>{pdf.text(pdf.splitTextToSize(`• ${a.texto}`,175),15,y);y+=8;});pdf.save(`Resumen_Diario_${fecha}.pdf`);};
  return <section className="grid min-w-0 gap-5">{loading&&<Loader/>}<header className="rounded-xl border border-teal-100 bg-gradient-to-r from-teal-50 via-white to-sky-50 p-5 shadow-sm"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wide text-teal-700">Control diario</p><h1 className="mt-1 text-3xl font-black text-slate-900">Resumen diario de actividades</h1><p className="mt-1 max-w-2xl text-sm text-slate-600">Consulta todas las actividades, atenciones, pagos y registros realizados durante el día seleccionado.</p></div><div className="flex flex-wrap items-end gap-2"><Input compact label="Fecha seleccionada" type="date" value={fecha} onChange={e=>changeDate(e.target.value)}/><Button variant="secondary" onClick={()=>changeDate(today())}><CalendarDays size={16}/>Hoy</Button><Button variant="secondary" onClick={()=>load(tab,true)}><RefreshCw size={16}/>Actualizar</Button><Button variant="secondary" onClick={exportExcel}><FileSpreadsheet size={16}/>Exportar Excel</Button><Button onClick={downloadPdf}><Download size={16}/>Descargar PDF</Button></div></div></header>
    <nav className="flex overflow-x-auto rounded-xl border border-slate-200 bg-white p-1 shadow-sm">{tabs.map(([key,label])=><button key={key} onClick={()=>{setTab(key);setQuery('')}} className={`flex min-w-max items-center gap-2 rounded-lg px-4 py-3 text-sm font-bold transition ${tab===key?'bg-teal-600 text-white':'text-slate-600 hover:bg-teal-50'}`}>{label}<span className={`rounded-full px-2 py-0.5 text-[10px] ${tab===key?'bg-white/20':'bg-slate-100'}`}>{counts[key]??0}</span></button>)}</nav>
    {tab==='resumen'?<Summary data={current} onTab={setTab}/>:<div className="panel grid gap-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black text-slate-900">{tabs.find(x=>x[0]===tab)?.[1]}</h2><p className="text-sm text-slate-500">Registros correspondientes al {formatDate(fecha)}.</p></div>{tab==='observaciones'&&<Button onClick={()=>setShowObservation(true)}><Plus size={16}/>Nueva observación</Button>}{tab==='personal'&&<Button variant="secondary" onClick={()=>navigate('/personal/actividades')}><Plus size={16}/>Agregar tarea adicional</Button>}</div><SearchBar value={query} onChange={setQuery}/><TabContent tab={tab} rows={rows} navigate={navigate} onStaff={setStaffDetail}/></div>}
    <Modal open={showObservation} title="Nueva observación" subtitle={`Registro manual del ${formatDate(fecha)}.`} onClose={()=>setShowObservation(false)} size="compact"><ObservationForm fecha={fecha} patients={patients} professionals={professionals} onClose={()=>setShowObservation(false)} onSaved={()=>load('observaciones',true)}/></Modal>
    <Modal open={Boolean(staffDetail)} title="Detalle de actividades" subtitle={staffDetail?.nombre} onClose={()=>setStaffDetail(null)} size="compact"><div className="grid gap-3">{staffDetail?.actividades?.length?staffDetail.actividades.map((a,i)=><div key={i} className="border-l-4 border-teal-500 bg-teal-50/50 p-3"><b>{a.hora} · {a.tipo}</b><p className="text-sm text-slate-700">{a.descripcion}</p><span className="text-xs text-slate-500">{a.modulo}{a.paciente?` · ${a.paciente}`:''}</span></div>):<div className="empty-state">No existe detalle adicional en la bitácora.</div>}</div></Modal>
  </section>;
}

function Summary({data,onTab}) { const i=data.indicadores||{};return <div className="grid gap-5"><div className="grid grid-cols-2 gap-3 md:grid-cols-4 xl:grid-cols-7"><Metric label="Pacientes atendidos" value={i.pacientes_atendidos||0} icon={Users}/><Metric label="Pacientes nuevos" value={i.pacientes_nuevos||0} icon={UserRound} tone="blue"/><Metric label="Sesiones realizadas" value={i.sesiones_realizadas||0} icon={CalendarCheck} tone="green"/><Metric label="Faltas" value={i.faltas||0} icon={XCircle} tone="red"/><Metric label="Sesiones pendientes" value={i.sesiones_pendientes||0} icon={Activity} tone="amber"/><Metric label="Historias creadas" value={i.historias_creadas||0} icon={ClipboardList}/><Metric label="Evolutivos" value={i.evolutivos_registrados||0} icon={HeartPulse} tone="green"/><Metric label="Evolutivos pendientes" value={i.evolutivos_pendientes||0} icon={History} tone="amber"/><Metric label="Informes" value={i.informes_generados||0} icon={FileText} tone="blue"/><Metric label="Total cobrado" value={money(i.total_cobrado)} icon={Banknote} tone="green"/><Metric label="Total pendiente" value={money(i.total_pendiente)} icon={WalletCards} tone="red"/><Metric label="Pagos registrados" value={i.pagos_registrados||0} icon={CheckCircle2}/><Metric label="Fármacos aplicados" value={i.farmacos_aplicados||0} icon={Pill} tone="violet"/><Metric label="Personal activo" value={i.personal_actividad||0} icon={Stethoscope} tone="blue"/></div><div className="grid gap-4 xl:grid-cols-3"><MiniList title="Últimas atenciones" rows={data.ultimas_atenciones||[]} render={r=><><b>{r.hora} · {r.paciente}</b><span>Sesión {r.numero_sesion} · {r.evolutivo}</span></>} action={()=>onTab('atenciones')}/><MiniList title="Últimos pagos" rows={data.ultimos_pagos||[]} render={r=><><b>{r.hora} · {r.paciente}</b><span>{r.concepto} · {money(r.monto)} · {r.metodo}</span></>} action={()=>onTab('pagos')}/><section className="rounded-xl border border-amber-100 bg-amber-50/50 p-4"><h3 className="flex items-center gap-2 font-black text-amber-800"><AlertTriangle size={18}/>Alertas importantes</h3><div className="mt-3 grid gap-2">{data.alertas?.length?data.alertas.map((a,index)=><p key={index} className="rounded-lg bg-white p-2 text-sm text-slate-700"><b>{a.tipo}:</b> {a.texto}</p>):<p className="text-sm text-slate-500">No existen alertas reales para esta fecha.</p>}</div></section></div></div>; }
function MiniList({title,rows,render,action}) { return <section className="rounded-xl border border-slate-200 bg-white p-4"><h3 className="font-black text-slate-900">{title}</h3><div className="mt-3 grid gap-2">{rows.length?rows.map((r,i)=><div key={r.id||i} className="rounded-lg bg-slate-50 p-2 text-sm">{render(r)}</div>):<p className="text-sm text-slate-500">Sin registros.</p>}</div><button onClick={action} className="mt-3 text-xs font-black text-teal-700">Ver todos</button></section>; }

function TabContent({tab,rows,navigate,onStaff}) {
  const action=(label,icon,tone,path,state)=><ActionButton label={label} icon={icon} tone={tone} className="h-9 w-9" onClick={()=>navigate(path,state?{state}:undefined)}/>;
  const related=(row,primary)=><div className="flex flex-wrap gap-1.5">{primary}{row.paciente_id&&action('Ver paciente',UserRound,'edit',`/pacientes/${row.paciente_id}`)}{row.historia_id&&action('Ver historia clínica',ClipboardList,'download',`/historias-clinicas/${row.historia_id}`)}</div>;
  if(tab==='atenciones')return <DataView rows={rows} empty="No se registraron atenciones durante el día seleccionado." columns={[{key:'hora',label:'Hora'},{key:'paciente',label:'Paciente'},{key:'historia',label:'Historia clínica',wide:true},{key:'numero_sesion',label:'Sesión'},{key:'asistencia',label:'Asistencia'},{key:'profesional',label:'Profesional'},{key:'evolutivo',label:'Evolutivo'},{key:'dolor_inicial',label:'Dolor inicial',render:r=>pain(r.dolor_inicial)},{key:'dolor_final',label:'Dolor final',render:r=>pain(r.dolor_final)}]} actions={r=>related(r,action('Ver sesión',CalendarCheck,'view','/sesiones',{verSesionId:r.id}))}/>;
  if(tab==='pagos')return <DataView rows={rows} empty="No se registraron pagos durante el día seleccionado." columns={[{key:'hora',label:'Hora'},{key:'paciente',label:'Paciente'},{key:'concepto',label:'Concepto pagado',wide:true},{key:'historia',label:'Historia / sesión'},{key:'monto',label:'Monto',render:r=>money(r.monto)},{key:'metodo',label:'Método'},{key:'saldo',label:'Saldo',render:r=>money(r.saldo)},{key:'estado',label:'Estado'},{key:'recibido_por',label:'Recibido por'}]} actions={r=>related(r,action('Ver pago y deuda',WalletCards,'view','/control-financiero/planilla-pagos',{conceptoCobroId:r.concepto_id||r.id}))}/>;
  if(tab==='deudas')return <div className="grid gap-5"><DebtGroup title="Deudas generadas hoy" rows={rows.filter(r=>r.origen==='Generada hoy')} related={related} navigate={navigate}/><DebtGroup title="Deudas anteriores pendientes" rows={rows.filter(r=>r.origen==='Anterior')} related={related} navigate={navigate}/></div>;
  if(tab==='evolutivos')return <DataView rows={rows} empty="No se registraron evolutivos." columns={[{key:'hora',label:'Hora'},{key:'paciente',label:'Paciente'},{key:'historia',label:'Historia clínica'},{key:'numero_sesion',label:'Sesión'},{key:'procedimiento',label:'Procedimiento / evolución',wide:true},{key:'dolor_inicial',label:'Dolor inicial',render:r=>pain(r.dolor_inicial)},{key:'dolor_final',label:'Dolor final',render:r=>pain(r.dolor_final)},{key:'profesional',label:'Profesional'},{key:'estado',label:'Estado'}]} actions={r=>related(r,action('Ver evolutivo',HeartPulse,'view','/evolutivos-clinicos',{sesionId:r.id,historiaId:r.historia_id}))}/>;
  if(tab==='farmacos')return <DataView rows={rows} empty="No se aplicaron fármacos durante el día seleccionado." columns={[{key:'hora',label:'Hora'},{key:'paciente',label:'Paciente'},{key:'historia',label:'Historia clínica'},{key:'sesion',label:'Sesión'},{key:'farmaco',label:'Fármaco'},{key:'dosis',label:'Dosis'},{key:'via',label:'Vía'},{key:'profesional',label:'Profesional'},{key:'observacion',label:'Observaciones',wide:true}]} actions={r=>related(r,<div className="flex gap-1.5">{action('Ver fármaco',Pill,'view',`/documentos/administracion-farmacos?paciente_id=${r.paciente_id}`)}{action('Ver sesión',CalendarCheck,'print','/sesiones',{verSesionId:r.id})}</div>)}/>;
  if(tab==='personal')return <DataView rows={rows} empty="No se registró actividad del personal." columns={[{key:'nombre',label:'Personal'},{key:'cargo',label:'Cargo'},{key:'pacientes',label:'Pacientes'},{key:'sesiones',label:'Sesiones'},{key:'evolutivos',label:'Evolutivos'},{key:'pagos',label:'Pagos'},{key:'historias',label:'Historias'},{key:'informes',label:'Informes'},{key:'tareas',label:'Tareas'},{key:'total',label:'Total'}]} actions={r=><button className="rounded-lg border border-teal-100 bg-teal-50 p-2 text-teal-700" onClick={()=>onStaff(r)}><Eye size={16}/></button>}/>;
  return <DataView rows={rows} empty="No se registraron observaciones." columns={[{key:'hora',label:'Hora'},{key:'categoria',label:'Categoría'},{key:'descripcion',label:'Descripción',wide:true},{key:'paciente',label:'Paciente'},{key:'personal',label:'Registrado por'},{key:'estado',label:'Estado'}]}/>;
}
function DebtGroup({title,rows,related,navigate}) { return <section><h3 className="mb-2 font-black text-slate-800">{title} <span className="ml-1 rounded-full bg-teal-50 px-2 py-1 text-xs text-teal-700">{rows.length}</span></h3><DataView rows={rows} empty={title.includes('hoy')?'No existen deudas generadas durante esta fecha.':'No existen deudas anteriores pendientes.'} columns={[{key:'paciente',label:'Paciente'},{key:'historia',label:'Historia clínica'},{key:'concepto',label:'De qué debe',wide:true},{key:'fecha_origen',label:'Fecha',render:r=>formatDate(r.fecha_origen)},{key:'monto_esperado',label:'Costaba',render:r=>money(r.monto_esperado)},{key:'total_pagado',label:'Pagó',render:r=>money(r.total_pagado)},{key:'saldo',label:'Debe',render:r=>money(r.saldo)},{key:'ultimo_pago',label:'Último pago',render:r=>formatDate(r.ultimo_pago)},{key:'estado',label:'Estado'}]} actions={r=>related(r,<ActionButton label="Ver deuda y pagos" icon={WalletCards} tone="view" className="h-9 w-9" onClick={()=>navigate('/control-financiero/planilla-pagos',{state:{conceptoCobroId:r.concepto_id||r.id}})}/>)}/></section>; }

export default ResumenDiario;
