import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Banknote, CalendarDays, Download, Eye, History, Info, Landmark, ReceiptText, RefreshCw, Save, ShieldCheck, Undo2, UserRound, WalletCards } from 'lucide-react';
import Swal from 'sweetalert2';
import Button from '../../components/common/Button';
import Input from '../../components/common/Input';
import Modal from '../../components/common/Modal';
import { useAuth } from '../../context/AuthContext';
import { getArqueoActual, getArqueoDetalle, getArqueosPago, previewArqueoPago, reopenArqueoPago, saveArqueoPago } from '../../services/planillaPagosService';
import { boliviaDate, formatBoliviaDateTime } from '../../utils/boliviaDateTime';
import ConsolidadoFinanciero from './ConsolidadoFinanciero';

const METHODS = ['Efectivo', 'QR', 'Transferencia', 'Tarjeta', 'Otro'];
const keys = { Efectivo: 'efectivo_contado', QR: 'qr_confirmado', Transferencia: 'transferencia_confirmada', Tarjeta: 'tarjeta_confirmada', Otro: 'otro_confirmado' };
const diffKeys = { Efectivo: 'diferencia_efectivo', QR: 'diferencia_qr', Transferencia: 'diferencia_transferencia', Tarjeta: 'diferencia_tarjeta', Otro: 'diferencia_otro' };
const money = (value) => `Bs ${Number(value || 0).toLocaleString('es-BO', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const date = (value) => value ? formatBoliviaDateTime(`${value}T12:00:00-04:00`, { dateStyle: 'short' }) : '—';
const closingDateTime = (arqueo) => {
  const value = arqueo?.snapshot_resumen?.cerrado_en_snapshot ?? arqueo?.cerrado_en;
  return value ? formatBoliviaDateTime(value, { dateStyle: 'short', timeStyle: 'short' }) : '—';
};
const initials = (value) => String(value || '').trim().split(/\s+/).slice(0, 2).map((part) => part[0]).join('').toUpperCase() || 'PA';
const blank = { efectivo_contado: '', qr_confirmado: '', transferencia_confirmada: '', tarjeta_confirmada: '', otro_confirmado: '', saldo_inicial_manual: '', monto_retirado: '', observacion: '' };

const downloadPdf = async (arqueo) => {
  const { jsPDF } = await import('jspdf');
  const pdf = new jsPDF({ unit: 'mm', format: 'a4' });
  const snap = arqueo.snapshot_resumen || {}; const margin = 15; const contentWidth = 180; const bottom = 280; let y = 14;
  const formatBs = (value) => `Bs ${Number(value || 0).toLocaleString('es-BO', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  const formatDate = (value) => { const match=String(value||'').match(/^(\d{4})-(\d{2})-(\d{2})/); return match?`${match[3]}/${match[2]}/${match[1]}`:'—'; };
  const smallHeader = () => { pdf.setTextColor(15,118,110);pdf.setFont('helvetica','bold');pdf.setFontSize(9);pdf.text('PHYSIO ACTIVE',margin,12);pdf.setTextColor(71,85,105);pdf.text('ARQUEO DE CAJA',195,12,{align:'right'});pdf.setDrawColor(203,213,225);pdf.line(margin,15,195,15);y=21; };
  const ensureSpace = (height) => { if (y+height<=bottom) return false;pdf.addPage();smallHeader();return true; };
  const section = (title) => { ensureSpace(12);y+=3;pdf.setFillColor(240,253,250);pdf.roundedRect(margin,y-5,contentWidth,8,1,1,'F');pdf.setTextColor(15,118,110);pdf.setFont('helvetica','bold');pdf.setFontSize(9);pdf.text(title,margin+3,y);pdf.setTextColor(30,41,59);y+=7; };
  const empty = (text) => { ensureSpace(9);pdf.setFont('helvetica','italic');pdf.setFontSize(8);pdf.setTextColor(100);pdf.text(text,margin+2,y+3);y+=8;pdf.setTextColor(30,41,59); };
  const table = (headers, rows, widths, aligns=[]) => {
    const drawHeader=()=>{ensureSpace(9);let x=margin;pdf.setFillColor(241,245,249);pdf.rect(margin,y,contentWidth,8,'F');pdf.setFont('helvetica','bold');pdf.setFontSize(7);pdf.setTextColor(71,85,105);headers.forEach((header,index)=>{pdf.text(header,x+(aligns[index]==='right'?widths[index]-2:aligns[index]==='center'?widths[index]/2:2),y+5,{align:aligns[index]||'left',maxWidth:widths[index]-4});x+=widths[index];});y+=8;};
    drawHeader();
    rows.forEach((row)=>{const cells=row.map((value,index)=>pdf.splitTextToSize(String(value??'—'),widths[index]-4));const rowHeight=Math.max(8,...cells.map(lines=>lines.length*3.5+3));if(ensureSpace(rowHeight))drawHeader();let x=margin;pdf.setFont('helvetica','normal');pdf.setFontSize(7.5);pdf.setTextColor(30,41,59);cells.forEach((lines,index)=>{pdf.text(lines,x+(aligns[index]==='right'?widths[index]-2:aligns[index]==='center'?widths[index]/2:2),y+4,{align:aligns[index]||'left',maxWidth:widths[index]-4});x+=widths[index];});pdf.setDrawColor(226,232,240);pdf.line(margin,y+rowHeight,195,y+rowHeight);y+=rowHeight;});
  };
  pdf.setTextColor(15,118,110);pdf.setFont('helvetica','bold');pdf.setFontSize(16);pdf.text('PHYSIO ACTIVE',margin,y);pdf.setTextColor(30,41,59);pdf.setFontSize(12);pdf.text('ARQUEO DE CAJA',margin,y+7);pdf.setDrawColor(94,234,212);pdf.line(margin,y+11,195,y+11);y+=18;
  const headerFields=[['Código',arqueo.numero_arqueo],['Fecha',formatDate(arqueo.fecha_operativa)],['Responsable',snap.responsable_nombre_snapshot ?? arqueo.responsable?.nombre ?? '—'],['Resultado',snap.resultado??arqueo.resultado_cierre??'—'],['Saldo dejado',formatBs(snap.saldo_dejado_caja??arqueo.saldo_dejado_caja)]];
  headerFields.forEach(([label,value],index)=>{const col=index%3,row=Math.floor(index/3),x=margin+col*60,top=y+row*13;pdf.setFontSize(6.5);pdf.setFont('helvetica','bold');pdf.setTextColor(100);pdf.text(label.toUpperCase(),x,top);pdf.setFontSize(8.5);pdf.setTextColor(30,41,59);pdf.text(pdf.splitTextToSize(String(value),55),x,top+4);});y+=29;
  section('APERTURA Y SERVICIOS');
  table(['Saldo inicial','Total esperado','Total cobrado','Total pendiente','Pacientes con deuda'],[[formatBs(snap.saldo_inicial_efectivo??arqueo.saldo_inicial_efectivo),formatBs(snap.total_esperado??arqueo.total_esperado),formatBs(snap.total_cobrado??arqueo.total_cobrado),formatBs(snap.total_pendiente??arqueo.total_pendiente),snap.pacientes_deuda??arqueo.pacientes_deuda??0]],[36,36,36,36,36],['center','center','center','center','center']);
  section('CONCILIACIÓN');
  const reconciliation=METHODS.map(method=>[method,formatBs(snap.sistemas?.[method]),formatBs(snap.confirmados?.[method]),formatBs(snap.diferencias?.[diffKeys[method]])]);reconciliation.push(['TOTAL',formatBs(snap.total_sistema),formatBs(snap.total_confirmado),formatBs(snap.diferencia_total)]);table(['Método','Sistema','Confirmado','Diferencia'],reconciliation,[54,42,42,42],['left','right','right','right']);
  section('EFECTIVO DETALLADO');
  const cashDetail=[['Saldo inicial en efectivo','saldo_inicial_efectivo'],['Cobros de pacientes en efectivo','pagos_pacientes_efectivo'],['Otros ingresos en efectivo','ingresos_extraordinarios_efectivo'],['Aportes','aportes'],['Ajustes positivos','ajustes_positivos'],['Egresos en efectivo','egresos_efectivo'],['Retiros manuales','retiros'],['Ajustes negativos','ajustes_negativos'],['Efectivo esperado','efectivo_esperado_cierre']].map(([label,key])=>[label,formatBs(snap[key])]);cashDetail.push(['Efectivo contado',formatBs(arqueo.efectivo_contado)],['Diferencia efectivo',formatBs(arqueo.diferencia_efectivo)]);table(['Concepto','Importe'],cashDetail,[130,50],['left','right']);
  section('PAGOS DE PACIENTES');
  const payments=(arqueo.movimientosSnapshot||[]).map((row,index)=>[index+1,String(row.hora||'').slice(0,5)||'—',row.paciente_nombre_snapshot,row.metodo_snapshot,formatBs(row.monto_snapshot)]);if(payments.length)table(['N°','Hora','Paciente','Método','Monto'],payments,[9,19,94,28,30],['center','center','left','center','right']);else empty('No existen pagos registrados para este arqueo.');
  section('PACIENTES NO CANCELADOS');
  const outstanding=(arqueo.obligacionesNoCanceladas||[]).map((row,index)=>[index+1,formatDate(row.fecha),row.paciente,formatBs(row.montoEsperado??row.monto_esperado),formatBs(row.montoPagado??row.monto_pagado),formatBs(row.saldoPendiente??row.saldo_pendiente),row.estadoReporte??row.estado_reporte??'—']);if(outstanding.length)table(['N°','Fecha','Paciente','Esperado','Pagado','Pendiente','Estado'],outstanding,[8,22,54,25,22,27,22],['center','center','left','right','right','right','center']);else empty('No existen obligaciones pendientes registradas para este arqueo.');
  table(['Resumen de deuda','Valor'],[['Total pendiente',formatBs(snap.total_pendiente??arqueo.total_pendiente)],['Registros con deuda',snap.pacientes_deuda??arqueo.pacientes_deuda??0]],[130,50],['left','right']);
  section('MOVIMIENTOS DE CAJA');
  const cashRows=(arqueo.movimientosCajaSnapshot||[]).map(row=>[String(row.hora||'').slice(0,5)||'—',String(row.tipo_movimiento_snapshot||'—').replaceAll('_',' '),row.descripcion_snapshot||row.concepto_snapshot||'—',row.metodo_snapshot,formatBs(row.monto_snapshot),row.usuario_snapshot||'—']);if(cashRows.length)table(['Hora','Tipo','Descripción','Método','Monto','Responsable'],cashRows,[17,28,50,23,25,37],['center','left','left','center','right','left']);else empty('No existen movimientos de caja registrados para este arqueo.');
  section('RESUMEN DEL CIERRE');
  table(['Campo','Valor'],[['Monto retirado',formatBs(snap.monto_retirado??arqueo.monto_retirado)],['Saldo dejado en caja',formatBs(snap.saldo_dejado_caja??arqueo.saldo_dejado_caja)],['Total pendiente',formatBs(snap.total_pendiente??arqueo.total_pendiente)],['Estado original',snap.estado_cierre_snapshot ?? arqueo.estado ?? '—'],['Resultado',snap.resultado??arqueo.resultado_cierre??'—'],['Observación',snap.observacion_snapshot ?? arqueo.observacion ?? 'Sin observación'],['Fecha/hora de cierre',closingDateTime(arqueo)]],[60,120],['left','left']);
  const pages=pdf.getNumberOfPages();for(let page=1;page<=pages;page+=1){pdf.setPage(page);pdf.setFont('helvetica','normal');pdf.setFontSize(7);pdf.setTextColor(100);pdf.text('Physio Active · Documento histórico',margin,290);pdf.text(`Página ${page} de ${pages}`,195,290,{align:'right'});}
  pdf.save(`arqueo_${arqueo.numero_arqueo || arqueo.id}.pdf`);
};

function Arqueos() {
  const { isAdmin } = useAuth(); const today = boliviaDate();
  const [tab,setTab]=useState('actual'); const [actual,setActual]=useState(null); const [preview,setPreview]=useState(null); const [history,setHistory]=useState([]); const [detail,setDetail]=useState(null); const [form,setForm]=useState(blank); const [loading,setLoading]=useState(true);
  const set=(k,v)=>setForm(o=>({...o,[k]:v}));
  const load=useCallback(async()=>{setLoading(true);try{const [a,h]=await Promise.all([getArqueoActual(today),getArqueosPago()]);setActual(a);setHistory(h);if(a.arqueo?.estado==='Borrador')setForm(o=>({...o,...Object.fromEntries(METHODS.map(m=>[keys[m],a.arqueo[diffKeys[m]]==null?'':(a.arqueo[keys[m]]??'')])),monto_retirado:a.arqueo.monto_retirado??'',observacion:a.arqueo.observacion??'',saldo_inicial_manual:a.arqueo.saldo_inicial_manual?a.arqueo.saldo_inicial_efectivo:o.saldo_inicial_manual}));}catch(e){Swal.fire({icon:'error',title:'No se pudo cargar arqueos',text:e.message});}finally{setLoading(false)}},[today]);
  useEffect(()=>{load()},[load]);
  useEffect(()=>{if(!actual||actual.arqueo?.estado==='Cerrado'){setPreview(null);return undefined}const timer=setTimeout(async()=>{try{setPreview(await previewArqueoPago({...form,fecha_operativa:today}))}catch{setPreview(null)}},250);return()=>clearTimeout(timer)},[actual,form,today]);
  const isClosed=actual?.arqueo?.estado==='Cerrado';
  const storedDisplay=isClosed?actual:(preview||actual);
  const display=isClosed?{...storedDisplay,total_pendiente:storedDisplay.deuda_vigente_actual,pacientes_deuda:storedDisplay.pacientes_deuda_actual}:storedDisplay;
  const systems=display?.sistemas||{};
  const differences=useMemo(()=>Object.fromEntries(METHODS.map(m=>[m,display?.diferencias?.[diffKeys[m]]??null])),[display]);
  const totalSystem=Number(display?.total_sistema||0); const totalConfirmed=display?.total_confirmado??null;
  const save=async(cerrar)=>{try{await saveArqueoPago({...form,fecha_operativa:today,cerrar});await Swal.fire({icon:'success',title:cerrar?'Arqueo cerrado':'Borrador guardado',timer:1300,showConfirmButton:false});setForm(blank);await load()}catch(e){Swal.fire({icon:'error',title:'No se pudo guardar',text:e.message})}};
  const openDetail=async(id)=>{try{setDetail(await getArqueoDetalle(id))}catch(e){Swal.fire({icon:'error',title:'No se pudo abrir el detalle',text:e.message})}};
  if(loading)return <div className="panel py-20 text-center text-slate-500">Cargando control de arqueo…</div>;
  return <section className="grid gap-5">
    <header className="rounded-xl border border-teal-100 bg-gradient-to-r from-teal-50 via-white to-sky-50 p-5"><p className="text-xs font-black uppercase text-teal-700">Control financiero</p><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-black">Arqueos</h1><p className="text-sm text-slate-600">Cierre diario, conciliación, historial y consolidado.</p></div><Button variant="secondary" onClick={load}><RefreshCw size={16}/>Actualizar</Button></div></header>
    <nav className="grid grid-cols-3 gap-2 rounded-xl border bg-white p-2">{[['actual','Arqueo actual',Landmark],['historial','Historial',History],['consolidado','Consolidado',CalendarDays]].map(([k,l,I])=><button key={k} onClick={()=>setTab(k)} className={`flex min-h-11 items-center justify-center gap-2 rounded-lg text-sm font-bold ${tab===k?'bg-teal-600 text-white':'text-slate-600 hover:bg-teal-50'}`}><I size={17}/>{l}</button>)}</nav>
    {tab==='actual'&&<><div className="grid gap-3 md:grid-cols-5">{[['Fecha operativa',date(display.fecha_operativa)],['Estado',actual.arqueo?.estado||'Sin iniciar'],['Responsable',actual.arqueo?.responsable?.nombre||'Pendiente'],['Saldo inicial',display.apertura_pendiente?'Pendiente de definir':money(display.saldo_inicial_efectivo)],['Origen',display.requiere_saldo_inicial_manual?'Ingresado manualmente':'Cierre diario anterior']].map(([l,v])=><div key={l} className="rounded-xl border bg-white p-3"><span className="text-xs font-black uppercase text-slate-500">{l}</span><b className="mt-1 block">{v}</b></div>)}</div>
      <div className="grid gap-4 lg:grid-cols-[1fr_1.3fr]"><div className="panel"><h2 className="font-black">Resumen de servicios</h2><div className="mt-3 grid grid-cols-2 gap-2">{[['Total esperado por servicios',display.total_esperado],['Cobros de pacientes del período',display.total_cobrado],['Deuda vigente por servicios',display.total_pendiente],['Pacientes con deuda',display.pacientes_deuda]].map(([l,v])=><div key={l} className="group relative rounded-lg bg-slate-50 p-3"><span className="text-xs text-slate-500">{l}</span>{l==='Total esperado por servicios'&&<><Info aria-label="Información sobre el total esperado" size={14} className="ml-1 inline text-slate-400"/><span role="tooltip" className="pointer-events-none absolute bottom-full left-2 z-20 mb-2 hidden w-64 rounded-lg bg-slate-800 p-2 text-xs font-normal text-white shadow-lg group-hover:block">Suma de todos los servicios del período: incluye lo cobrado y lo que todavía está pendiente. No representa el efectivo disponible en caja.</span></>}<b className="block">{l.includes('Pacientes')?v:money(v)}</b></div>)}</div><div className="mt-4 rounded-lg border border-sky-100 bg-sky-50 p-3"><div className="flex items-start gap-2"><Info size={17} className="mt-0.5 shrink-0 text-sky-700"/><div><span className="text-xs font-bold text-sky-800">Otros ingresos registrados por cualquier método</span><b className="block text-lg">{money(display.ingresos_extraordinarios)}</b><p className="mt-1 text-xs text-slate-600">Puede incluir QR, transferencia, tarjeta u otros medios. Solo la parte recibida en efectivo aumenta el dinero físico de la caja.</p></div></div></div><h3 className="mt-5 font-black">Dinero físico en caja</h3><p className="mt-1 text-xs text-slate-500">Aquí se muestran únicamente los movimientos que aumentan o disminuyen el efectivo.</p><div className="mt-2 grid gap-1 text-sm">{[['Saldo inicial en efectivo',display.saldo_inicial_efectivo],['Cobros de pacientes en efectivo',display.pagos_pacientes_efectivo],['Otros ingresos en efectivo',display.ingresos_extraordinarios_efectivo],['Aportes en efectivo',display.aportes],['Ajustes positivos',display.ajustes_positivos],['Egresos pagados en efectivo',display.egresos_efectivo],['Retiros manuales',display.retiros],['Ajustes negativos',display.ajustes_negativos],['EFECTIVO ESPERADO EN CAJA',display.efectivo_esperado_cierre]].map(([l,v])=><div key={l} className={`flex justify-between rounded px-2 py-1 ${l.includes('ESPERADO')?'bg-teal-50 font-black':''}`}><span>{l}</span><b>{money(v)}</b></div>)}</div></div>
      <div className="panel"><h2 className="font-black">Conciliación de métodos</h2>{Number(actual.efectivo_esperado_cierre)<0&&!isClosed&&<div className="mt-3 flex gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertTriangle size={18}/>El efectivo esperado es negativo. Registre un aporte o corrija movimientos antes del cierre.</div>}{isClosed&&<div className="mt-3 flex gap-3 rounded-xl border border-teal-200 bg-teal-50 p-4 text-teal-800"><ShieldCheck size={20} className="shrink-0"/><div><strong className="block text-sm">Arqueo diario cerrado</strong><p className="mt-1 text-xs">Los valores que se muestran corresponden al cierre guardado y ya no pueden modificarse.</p></div></div>}<div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs uppercase text-slate-500"><th>Método</th><th>Sistema</th><th>Confirmado</th><th>Diferencia</th></tr></thead><tbody>{METHODS.map(m=><tr key={m} className="border-t"><td className="py-3 font-bold">{m}</td><td>{money(systems[m])}</td><td>{isClosed?<b>{money(actual.arqueo?.snapshot_resumen?.confirmados?.[m]??actual.arqueo?.[keys[m]])}</b>:<input aria-label={`${m} confirmado`} type="number" min="0" step="0.01" className="w-28 rounded-lg border px-2 py-1" placeholder={Number(systems[m])===0?'0':'Pendiente'} value={form[keys[m]]} onChange={e=>set(keys[m],e.target.value)}/>}</td><td className={differences[m]===null?'text-amber-600':differences[m]===0?'text-emerald-600':'text-red-600'}>{differences[m]===null?'Pendiente de confirmar':money(differences[m])}</td></tr>)}</tbody><tfoot><tr className="border-t-2 font-black"><td>TOTAL</td><td>{money(totalSystem)}</td><td>{totalConfirmed===null?'Pendiente':money(totalConfirmed)}</td><td>{totalConfirmed===null?'Pendiente':money(totalConfirmed-totalSystem)}</td></tr></tfoot></table></div>
      {isClosed?<div className="mt-4 grid gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 sm:grid-cols-3"><div><small className="text-slate-500">Saldo inicial registrado</small><b className="block">{money(actual.saldo_inicial_efectivo)}</b></div><div><small className="text-slate-500">Monto retirado</small><b className="block">{money(actual.arqueo?.monto_retirado)}</b></div><div><small className="text-slate-500">Saldo dejado en caja</small><b className="block text-teal-700">{money(actual.arqueo?.saldo_dejado_caja)}</b></div></div>:<>{!actual.requiere_saldo_inicial_manual?<div className="mt-4 flex gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-800"><Info size={20} className="mt-0.5 shrink-0"/><div><strong className="block text-sm">Saldo inicial automático</strong><b className="mt-1 block text-lg">{money(actual.saldo_inicial_efectivo)}</b><p className="mt-1 text-xs">Heredado del cierre del {date(actual.saldo_inicial_origen?.fecha_operativa)}</p><p className="mt-1 text-xs">Este monto corresponde al dinero que quedó en caja en el último cierre diario.</p></div></div>:<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50/60 p-4"><div className="mb-3 flex gap-2 text-amber-800"><Info size={19} className="mt-0.5 shrink-0"/><div><strong className="block text-sm">Saldo inicial manual</strong><p className="mt-1 text-xs">No existe un cierre diario anterior válido. Ingresa el efectivo con el que inicia la caja hoy.</p></div></div><Input label="Saldo inicial manual" type="number" min="0" step="0.01" value={form.saldo_inicial_manual} onChange={e=>set('saldo_inicial_manual',e.target.value)}/><p className="mt-2 flex items-center gap-1.5 text-xs text-slate-600"><Info size={14}/>Registra únicamente el efectivo disponible al comenzar la jornada.</p></div>}<div className="mt-3 grid gap-3 sm:grid-cols-2"><Input label="Monto a retirar al cierre" type="number" min="0" step="0.01" value={form.monto_retirado} onChange={e=>set('monto_retirado',e.target.value)}/><Input label="Observación" multiline value={form.observacion} onChange={e=>set('observacion',e.target.value)}/></div><div className="mt-4 flex justify-end gap-2"><Button variant="secondary" onClick={()=>save(false)}><Save size={16}/>Guardar borrador</Button><Button onClick={()=>save(true)} disabled={Number(actual.efectivo_esperado_cierre)<0}><ShieldCheck size={16}/>Cerrar arqueo</Button></div></>}</div></div></>}
    {tab==='historial'&&<div className="panel overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs uppercase text-slate-500">{['Número','Fecha/hora de cierre','Responsable','Sistema','Confirmado','Diferencia','Resultado','Estado','Acciones'].map(x=><th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{history.map(a=>{const s=a.snapshot_resumen||{};return <tr key={a.id} className="border-t"><td className="p-2 font-bold">{a.numero_arqueo}</td><td>{closingDateTime(a)}</td><td>{a.responsable?.nombre}</td><td>{money(s.total_sistema)}</td><td>{s.total_confirmado==null?'—':money(s.total_confirmado)}</td><td>{s.diferencia_total==null?'—':money(s.diferencia_total)}</td><td>{a.resultado_cierre||'—'}</td><td>{a.estado}</td><td className="flex gap-1 p-2"><button title="Ver detalle" onClick={()=>openDetail(a.id)} className="rounded border p-2"><Eye size={15}/></button><button title="Descargar PDF" onClick={async()=>downloadPdf(await getArqueoDetalle(a.id))} className="rounded border p-2"><Download size={15}/></button>{a.estado==='Cerrado'&&isAdmin&&<button title="Reabrir" onClick={async()=>{const r=await Swal.fire({title:'Reabrir arqueo',input:'textarea',inputLabel:'Motivo obligatorio',showCancelButton:true});if(r.isConfirmed&&r.value){try{await reopenArqueoPago(a.id,r.value);load()}catch(e){Swal.fire({icon:'error',title:'No se pudo reabrir',text:e.message})}}}} className="rounded border p-2"><Undo2 size={15}/></button>}</td></tr>})}</tbody></table>{!history.length&&<p className="py-14 text-center text-slate-500">No existen arqueos.</p>}</div>}
    {tab==='consolidado'&&<ConsolidadoFinanciero/>}
    <Modal open={Boolean(detail)} title="Detalle del arqueo" subtitle={detail&&`${detail.numero_arqueo} · ${date(detail.fecha_operativa)}`} onClose={()=>setDetail(null)} size="compact" closeOnEscape>{detail&&(()=>{const payments=detail.movimientosSnapshot||[];const unpaid=detail.obligacionesNoCanceladas||[];const patientRows=[...payments.map(row=>({key:`p-${row.id}`,name:row.paciente_nombre_snapshot,method:row.metodo_snapshot,amount:row.monto_snapshot,state:'Cancelado'})),...unpaid.map(row=>({key:`u-${row.conceptoId||row.concepto_id}`,name:row.paciente,method:'—',amount:0,state:'No cancelado'}))];const cashMovements=detail.movimientosCajaSnapshot||[];const paymentTotal=payments.reduce((sum,row)=>sum+Number(row.monto_snapshot||0),0);const withdrawalTotal=cashMovements.filter(row=>row.tipo_movimiento_snapshot==='RETIRO_CAJA').reduce((sum,row)=>sum+Number(row.monto_snapshot||0),0);const result=detail.resultado_cierre||detail.snapshot_resumen?.resultado||'—';return <div className="grid gap-4">
      <div className="flex justify-end"><span className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-[11px] font-black uppercase ${result==='CUADRADO'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}><ShieldCheck size={14}/>{result.replaceAll('_',' ')}</span></div>
      <div className="grid grid-cols-2 gap-2 md:grid-cols-4">{[[CalendarDays,'Fecha/hora de cierre',closingDateTime(detail)],[UserRound,'Responsable',detail.snapshot_resumen?.responsable_nombre_snapshot||detail.responsable?.nombre||'—'],[ShieldCheck,'Resultado',result.replaceAll('_',' ')],[WalletCards,'Saldo dejado',money(detail.saldo_dejado_caja)]].map(([Icon,label,value])=><div key={label} className="flex min-w-0 items-start gap-3 rounded-xl border border-slate-200 bg-slate-50/70 p-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-teal-50 text-teal-700"><Icon size={18}/></span><div className="min-w-0"><small className="text-[10px] font-bold text-slate-500">{label}</small><b className="block break-words text-sm text-slate-800">{value}</b></div></div>)}</div>
      <section><h3 className="mb-2 flex items-center gap-2 text-sm font-black text-slate-800"><ReceiptText size={16} className="text-teal-700"/>Pacientes y cobros ({patientRows.length})</h3><div className="max-h-52 overflow-auto rounded-xl border border-slate-200"><table className="w-full min-w-[560px] text-left text-xs"><thead className="sticky top-0 bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="p-3">Paciente</th><th className="p-3">Método</th><th className="p-3 text-right">Monto</th><th className="p-3">Estado</th></tr></thead><tbody>{patientRows.map(row=><tr key={row.key} className="border-t border-slate-100"><td className="p-3"><div className="flex items-center gap-2"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-teal-50 text-[10px] font-black text-teal-700">{initials(row.name)}</span><b className="text-slate-800">{row.name}</b></div></td><td className="p-3"><span className="inline-flex rounded-md border border-slate-200 bg-white px-2 py-1 font-bold text-slate-600">{row.method||'—'}</span></td><td className="p-3 text-right font-black text-slate-800">{money(row.amount)}</td><td className="p-3"><span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-black ${row.state==='Cancelado'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{row.state}</span></td></tr>)}</tbody></table>{!patientRows.length&&<p className="p-5 text-center text-sm text-slate-500">Sin pacientes incluidos.</p>}</div></section>
      <section><h3 className="mb-2 flex items-center gap-2 text-sm font-black text-slate-800"><Banknote size={16} className="text-teal-700"/>Movimientos de caja congelados ({cashMovements.length})</h3><div className="grid gap-2">{cashMovements.map(row=><div key={row.id} className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 p-3"><div className="flex min-w-0 items-center gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-rose-50 text-rose-600"><Download size={17}/></span><div className="min-w-0"><b className="block text-sm text-slate-800">{String(row.tipo_movimiento_snapshot||'Movimiento').replaceAll('_',' ')}</b><span className="block truncate text-xs text-slate-500">{row.concepto_snapshot||'—'}</span></div></div><div className="shrink-0 text-right"><span className="rounded-md border px-2 py-1 text-[10px] font-bold text-slate-600">{row.metodo_snapshot||'—'}</span><b className="ml-3 text-sm text-rose-600">- {money(row.monto_snapshot)}</b></div></div>)}{!cashMovements.length&&<p className="rounded-xl border border-dashed p-4 text-center text-sm text-slate-500">Sin movimientos de caja incluidos.</p>}</div></section>
      <section className="rounded-xl border border-slate-200 bg-slate-50/70 p-3"><h3 className="mb-3 flex items-center gap-2 text-sm font-black"><Landmark size={16} className="text-teal-700"/>Resumen del cierre</h3><div className="grid grid-cols-3 divide-x divide-slate-200 text-center"><div><small className="text-slate-500">Pagos</small><b className="block text-sm text-emerald-700">{money(paymentTotal)}</b></div><div><small className="text-slate-500">Retiros</small><b className="block text-sm text-rose-600">- {money(withdrawalTotal)}</b></div><div><small className="text-slate-500">Saldo dejado</small><b className="block text-sm text-emerald-700">{money(detail.saldo_dejado_caja)}</b></div></div></section>
      <div className="flex justify-end border-t border-slate-200 pt-3"><Button onClick={()=>downloadPdf(detail)}><Download size={16}/>Descargar PDF A4</Button></div>
    </div>})()}</Modal>
  </section>;
}

export default Arqueos;
