import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CalendarDays, Download, Eye, History, Info, Landmark, RefreshCw, Save, ShieldCheck, Undo2 } from 'lucide-react';
import Swal from 'sweetalert2';
import Button from '../../components/common/Button';
import Input from '../../components/common/Input';
import Modal from '../../components/common/Modal';
import { useAuth } from '../../context/AuthContext';
import { getArqueoActual, getArqueoDetalle, getArqueosPago, previewArqueoPago, reopenArqueoPago, saveArqueoPago } from '../../services/planillaPagosService';
import { boliviaDate, formatBoliviaDateTime } from '../../utils/boliviaDateTime';
import ConsolidadoFinanciero from './ConsolidadoFinanciero';

const METHODS = ['Efectivo', 'QR', 'Transferencia', 'Tarjeta', 'Otro'];
const keys = { Efectivo: 'efectivo_contado', QR: 'qr_confirmado', Transferencia: 'transferencia_confirmada', Tarjeta: 'tarjeta_confirmada', Otro: 'otro_confirmado' };
const diffKeys = { Efectivo: 'diferencia_efectivo', QR: 'diferencia_qr', Transferencia: 'diferencia_transferencia', Tarjeta: 'diferencia_tarjeta', Otro: 'diferencia_otro' };
const money = (value) => `Bs ${Number(value || 0).toLocaleString('es-BO', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const date = (value) => value ? formatBoliviaDateTime(`${value}T12:00:00-04:00`, { dateStyle: 'short' }) : '—';
const blank = { efectivo_contado: '', qr_confirmado: '', transferencia_confirmada: '', tarjeta_confirmada: '', otro_confirmado: '', saldo_inicial_manual: '', monto_retirado: '', observacion: '' };

const addPdfPage = (pdf, title, number) => { if (number > 1) pdf.addPage(); pdf.setTextColor(15, 118, 110); pdf.setFont('helvetica', 'bold'); pdf.setFontSize(15); pdf.text('PHYSIO ACTIVE', 15, 14); pdf.setTextColor(30, 41, 59); pdf.setFontSize(11); pdf.text(title, 15, 22); pdf.line(15, 26, 195, 26); };
const downloadPdf = async (arqueo) => {
  const { jsPDF } = await import('jspdf'); const pdf = new jsPDF({ unit: 'mm', format: 'a4' }); let page = 1; let y = 34;
  const snap = arqueo.snapshot_resumen || {}; const line = (label, value) => { if (y > 275) { page += 1; addPdfPage(pdf, 'ARQUEO DE CAJA', page); y = 34; } pdf.setFont('helvetica', 'normal'); pdf.text(String(label), 15, y); pdf.setFont('helvetica', 'bold'); pdf.text(String(value ?? '—'), 195, y, { align: 'right' }); y += 6; };
  const section = (title) => { y += 3; pdf.setFillColor(240, 253, 250); pdf.rect(15, y - 5, 180, 8, 'F'); pdf.setTextColor(15, 118, 110); pdf.setFont('helvetica', 'bold'); pdf.text(title, 18, y); pdf.setTextColor(30, 41, 59); y += 8; };
  addPdfPage(pdf, 'ARQUEO DE CAJA', page);
  line('Número', arqueo.numero_arqueo); line('Fecha operativa', date(arqueo.fecha_operativa)); line('Responsable', snap.responsable_nombre_snapshot ?? arqueo.responsable?.nombre); line('Estado original / Resultado', `${snap.estado_cierre_snapshot ?? arqueo.estado} / ${snap.resultado ?? arqueo.resultado_cierre ?? '—'}`);
  section('APERTURA Y SERVICIOS'); line('Saldo inicial', money(snap.saldo_inicial_efectivo ?? arqueo.saldo_inicial_efectivo)); line('Origen', snap.saldo_inicial_origen?.numero_arqueo || (arqueo.saldo_inicial_manual ? 'Manual' : 'Sin arqueo anterior')); line('Total esperado servicios', money(snap.total_esperado ?? arqueo.total_esperado)); line('Total cobrado', money(snap.total_cobrado ?? arqueo.total_cobrado)); line('Total pendiente', money(snap.total_pendiente ?? arqueo.total_pendiente)); line('Pacientes con deuda', snap.pacientes_deuda ?? arqueo.pacientes_deuda);
  section('CONCILIACIÓN'); for (const method of METHODS) line(method, `Sistema ${money(snap.sistemas?.[method] ?? arqueo[method === 'Efectivo' ? 'efectivo_sistema' : `${method.toLowerCase()}_sistema`])} | Confirmado ${money(snap.confirmados?.[method] ?? arqueo[keys[method]])} | Diferencia ${money(snap.diferencias?.[diffKeys[method]] ?? arqueo[diffKeys[method]])}`); line('TOTAL', `Sistema ${money(snap.total_sistema)} | Confirmado ${money(snap.total_confirmado)} | Diferencia ${money(snap.diferencia_total)}`);
  section('EFECTIVO DETALLADO'); [['Saldo inicial en efectivo','saldo_inicial_efectivo'],['Cobros de pacientes en efectivo','pagos_pacientes_efectivo'],['Otros ingresos en efectivo','ingresos_extraordinarios_efectivo'],['Aportes en efectivo','aportes'],['Ajustes positivos','ajustes_positivos'],['Egresos pagados en efectivo','egresos_efectivo'],['Retiros manuales','retiros'],['Ajustes negativos','ajustes_negativos'],['Efectivo esperado','efectivo_esperado_cierre']].forEach(([l,k])=>line(l,money(snap[k]))); line('Efectivo contado', money(arqueo.efectivo_contado)); line('Diferencia efectivo', money(arqueo.diferencia_efectivo));
  section('PAGOS DE PACIENTES'); (arqueo.movimientosSnapshot || []).forEach((row)=>line(`${String(row.hora||'').slice(0,5)} · ${row.paciente_nombre_snapshot} · ${row.concepto_snapshot}`, `${row.metodo_snapshot} · ${money(row.monto_snapshot)}`)); if (!(arqueo.movimientosSnapshot||[]).length) line('Sin pagos incluidos','');
  section('MOVIMIENTOS DE CAJA'); (arqueo.movimientosCajaSnapshot || []).forEach((row)=>line(`${String(row.hora||'').slice(0,5)} · ${row.tipo_movimiento_snapshot} · ${row.concepto_snapshot}`, `${row.metodo_snapshot} · ${money(row.monto_snapshot)} · ${row.usuario_snapshot||''}`)); if (!(arqueo.movimientosCajaSnapshot||[]).length) line('Sin movimientos de caja incluidos','');
  section('CIERRE'); line('Monto retirado', money(snap.monto_retirado ?? arqueo.monto_retirado)); line('Saldo dejado en caja', money(snap.saldo_dejado_caja ?? arqueo.saldo_dejado_caja)); line('Observación', snap.observacion_snapshot ?? arqueo.observacion ?? 'Sin observación'); line('Fecha y hora', snap.cerrado_en_snapshot ? formatBoliviaDateTime(snap.cerrado_en_snapshot) : arqueo.cerrado_en ? formatBoliviaDateTime(arqueo.cerrado_en) : '—');
  const pages = pdf.getNumberOfPages(); for (let p=1;p<=pages;p+=1) { pdf.setPage(p); pdf.setFontSize(8); pdf.setTextColor(100); pdf.text(`Página ${p} de ${pages}`, 195, 290, { align:'right' }); pdf.text('Physio Active · Documento histórico', 15, 290); }
  pdf.save(`arqueo_${arqueo.numero_arqueo || arqueo.id}.pdf`);
};

function Arqueos() {
  const { isAdmin } = useAuth(); const today = boliviaDate();
  const [tab,setTab]=useState('actual'); const [actual,setActual]=useState(null); const [preview,setPreview]=useState(null); const [history,setHistory]=useState([]); const [detail,setDetail]=useState(null); const [form,setForm]=useState(blank); const [loading,setLoading]=useState(true);
  const set=(k,v)=>setForm(o=>({...o,[k]:v}));
  const load=useCallback(async()=>{setLoading(true);try{const [a,h]=await Promise.all([getArqueoActual(today),getArqueosPago()]);setActual(a);setHistory(h);if(a.arqueo?.estado==='Borrador')setForm(o=>({...o,...Object.fromEntries(METHODS.map(m=>[keys[m],a.arqueo[diffKeys[m]]==null?'':(a.arqueo[keys[m]]??'')])),monto_retirado:a.arqueo.monto_retirado??'',observacion:a.arqueo.observacion??'',saldo_inicial_manual:a.arqueo.saldo_inicial_manual?a.arqueo.saldo_inicial_efectivo:o.saldo_inicial_manual}));}catch(e){Swal.fire({icon:'error',title:'No se pudo cargar arqueos',text:e.message});}finally{setLoading(false)}},[today]);
  useEffect(()=>{load()},[load]);
  useEffect(()=>{if(!actual||actual.arqueo?.estado==='Cerrado'){setPreview(null);return undefined}const timer=setTimeout(async()=>{try{setPreview(await previewArqueoPago({...form,fecha_operativa:today}))}catch{setPreview(null)}},250);return()=>clearTimeout(timer)},[actual,form,today]);
  const isClosed=actual?.arqueo?.estado==='Cerrado';
  const storedDisplay=isClosed?actual:(preview||actual);
  const display=isClosed?{...storedDisplay,total_pendiente:storedDisplay.deuda_vigente_actual,pacientes_deuda:storedDisplay.pacientes_deuda_actual}:storedDisplay;
  const systems=display?.sistemas||{};
  const differences=useMemo(()=>Object.fromEntries(METHODS.map(m=>[m,display?.diferencias?.[diffKeys[m]]??null])),[display]);
  const totalSystem=Number(display?.total_sistema||0); const totalConfirmed=display?.total_confirmado??null;
  const save=async(cerrar)=>{try{await saveArqueoPago({...form,fecha_operativa:today,cerrar});await Swal.fire({icon:'success',title:cerrar?'Arqueo cerrado':'Borrador guardado',timer:1300,showConfirmButton:false});setForm(blank);await load()}catch(e){Swal.fire({icon:'error',title:'No se pudo guardar',text:e.message})}};
  const openDetail=async(id)=>{try{setDetail(await getArqueoDetalle(id))}catch(e){Swal.fire({icon:'error',title:'No se pudo abrir el detalle',text:e.message})}};
  if(loading)return <div className="panel py-20 text-center text-slate-500">Cargando control de arqueo…</div>;
  return <section className="grid gap-5">
    <header className="rounded-xl border border-teal-100 bg-gradient-to-r from-teal-50 via-white to-sky-50 p-5"><p className="text-xs font-black uppercase text-teal-700">Control financiero</p><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-3xl font-black">Arqueos</h1><p className="text-sm text-slate-600">Cierre diario, conciliación, historial y consolidado.</p></div><Button variant="secondary" onClick={load}><RefreshCw size={16}/>Actualizar</Button></div></header>
    <nav className="grid grid-cols-3 gap-2 rounded-xl border bg-white p-2">{[['actual','Arqueo actual',Landmark],['historial','Historial',History],['consolidado','Consolidado',CalendarDays]].map(([k,l,I])=><button key={k} onClick={()=>setTab(k)} className={`flex min-h-11 items-center justify-center gap-2 rounded-lg text-sm font-bold ${tab===k?'bg-teal-600 text-white':'text-slate-600 hover:bg-teal-50'}`}><I size={17}/>{l}</button>)}</nav>
    {tab==='actual'&&<><div className="grid gap-3 md:grid-cols-5">{[['Fecha operativa',date(display.fecha_operativa)],['Estado',actual.arqueo?.estado||'Sin iniciar'],['Responsable',actual.arqueo?.responsable?.nombre||'Pendiente'],['Saldo inicial',display.apertura_pendiente?'Pendiente de definir':money(display.saldo_inicial_efectivo)],['Origen',display.requiere_saldo_inicial_manual?'Ingresado manualmente':'Cierre diario anterior']].map(([l,v])=><div key={l} className="rounded-xl border bg-white p-3"><span className="text-xs font-black uppercase text-slate-500">{l}</span><b className="mt-1 block">{v}</b></div>)}</div>
      <div className="grid gap-4 lg:grid-cols-[1fr_1.3fr]"><div className="panel"><h2 className="font-black">Resumen de servicios</h2><div className="mt-3 grid grid-cols-2 gap-2">{[['Total esperado por servicios',display.total_esperado],['Cobros de pacientes del período',display.total_cobrado],['Deuda vigente por servicios',display.total_pendiente],['Pacientes con deuda',display.pacientes_deuda]].map(([l,v])=><div key={l} className="rounded-lg bg-slate-50 p-3"><span className="text-xs text-slate-500">{l}</span><b className="block">{l.includes('Pacientes')?v:money(v)}</b></div>)}</div><div className="mt-4 rounded-lg border border-sky-100 bg-sky-50 p-3"><div className="flex items-start gap-2"><Info size={17} className="mt-0.5 shrink-0 text-sky-700"/><div><span className="text-xs font-bold text-sky-800">Otros ingresos registrados por cualquier método</span><b className="block text-lg">{money(display.ingresos_extraordinarios)}</b><p className="mt-1 text-xs text-slate-600">Puede incluir QR, transferencia, tarjeta u otros medios. Solo la parte recibida en efectivo aumenta el dinero físico de la caja.</p></div></div></div><h3 className="mt-5 font-black">Dinero físico en caja</h3><p className="mt-1 text-xs text-slate-500">Aquí se muestran únicamente los movimientos que aumentan o disminuyen el efectivo.</p><div className="mt-2 grid gap-1 text-sm">{[['Saldo inicial en efectivo',display.saldo_inicial_efectivo],['Cobros de pacientes en efectivo',display.pagos_pacientes_efectivo],['Otros ingresos en efectivo',display.ingresos_extraordinarios_efectivo],['Aportes en efectivo',display.aportes],['Ajustes positivos',display.ajustes_positivos],['Egresos pagados en efectivo',display.egresos_efectivo],['Retiros manuales',display.retiros],['Ajustes negativos',display.ajustes_negativos],['EFECTIVO ESPERADO EN CAJA',display.efectivo_esperado_cierre]].map(([l,v])=><div key={l} className={`flex justify-between rounded px-2 py-1 ${l.includes('ESPERADO')?'bg-teal-50 font-black':''}`}><span>{l}</span><b>{money(v)}</b></div>)}</div></div>
      <div className="panel"><h2 className="font-black">Conciliación de métodos</h2>{Number(actual.efectivo_esperado_cierre)<0&&!isClosed&&<div className="mt-3 flex gap-2 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700"><AlertTriangle size={18}/>El efectivo esperado es negativo. Registre un aporte o corrija movimientos antes del cierre.</div>}{isClosed&&<div className="mt-3 flex gap-3 rounded-xl border border-teal-200 bg-teal-50 p-4 text-teal-800"><ShieldCheck size={20} className="shrink-0"/><div><strong className="block text-sm">Arqueo diario cerrado</strong><p className="mt-1 text-xs">Los valores que se muestran corresponden al cierre guardado y ya no pueden modificarse.</p></div></div>}<div className="mt-3 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs uppercase text-slate-500"><th>Método</th><th>Sistema</th><th>Confirmado</th><th>Diferencia</th></tr></thead><tbody>{METHODS.map(m=><tr key={m} className="border-t"><td className="py-3 font-bold">{m}</td><td>{money(systems[m])}</td><td>{isClosed?<b>{money(actual.arqueo?.snapshot_resumen?.confirmados?.[m]??actual.arqueo?.[keys[m]])}</b>:<input aria-label={`${m} confirmado`} type="number" min="0" step="0.01" className="w-28 rounded-lg border px-2 py-1" placeholder={Number(systems[m])===0?'0':'Pendiente'} value={form[keys[m]]} onChange={e=>set(keys[m],e.target.value)}/>}</td><td className={differences[m]===null?'text-amber-600':differences[m]===0?'text-emerald-600':'text-red-600'}>{differences[m]===null?'Pendiente de confirmar':money(differences[m])}</td></tr>)}</tbody><tfoot><tr className="border-t-2 font-black"><td>TOTAL</td><td>{money(totalSystem)}</td><td>{totalConfirmed===null?'Pendiente':money(totalConfirmed)}</td><td>{totalConfirmed===null?'Pendiente':money(totalConfirmed-totalSystem)}</td></tr></tfoot></table></div>
      {isClosed?<div className="mt-4 grid gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 sm:grid-cols-3"><div><small className="text-slate-500">Saldo inicial registrado</small><b className="block">{money(actual.saldo_inicial_efectivo)}</b></div><div><small className="text-slate-500">Monto retirado</small><b className="block">{money(actual.arqueo?.monto_retirado)}</b></div><div><small className="text-slate-500">Saldo dejado en caja</small><b className="block text-teal-700">{money(actual.arqueo?.saldo_dejado_caja)}</b></div></div>:<>{!actual.requiere_saldo_inicial_manual?<div className="mt-4 flex gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-800"><Info size={20} className="mt-0.5 shrink-0"/><div><strong className="block text-sm">Saldo inicial automático</strong><b className="mt-1 block text-lg">{money(actual.saldo_inicial_efectivo)}</b><p className="mt-1 text-xs">Heredado del cierre del {date(actual.saldo_inicial_origen?.fecha_operativa)}</p><p className="mt-1 text-xs">Este monto corresponde al dinero que quedó en caja en el último cierre diario.</p></div></div>:<div className="mt-4 rounded-xl border border-amber-200 bg-amber-50/60 p-4"><div className="mb-3 flex gap-2 text-amber-800"><Info size={19} className="mt-0.5 shrink-0"/><div><strong className="block text-sm">Saldo inicial manual</strong><p className="mt-1 text-xs">No existe un cierre diario anterior válido. Ingresa el efectivo con el que inicia la caja hoy.</p></div></div><Input label="Saldo inicial manual" type="number" min="0" step="0.01" value={form.saldo_inicial_manual} onChange={e=>set('saldo_inicial_manual',e.target.value)}/><p className="mt-2 flex items-center gap-1.5 text-xs text-slate-600"><Info size={14}/>Registra únicamente el efectivo disponible al comenzar la jornada.</p></div>}<div className="mt-3 grid gap-3 sm:grid-cols-2"><Input label="Monto a retirar al cierre" type="number" min="0" step="0.01" value={form.monto_retirado} onChange={e=>set('monto_retirado',e.target.value)}/><Input label="Observación" multiline value={form.observacion} onChange={e=>set('observacion',e.target.value)}/></div><div className="mt-4 flex justify-end gap-2"><Button variant="secondary" onClick={()=>save(false)}><Save size={16}/>Guardar borrador</Button><Button onClick={()=>save(true)} disabled={Number(actual.efectivo_esperado_cierre)<0}><ShieldCheck size={16}/>Cerrar arqueo</Button></div></>}</div></div></>}
    {tab==='historial'&&<div className="panel overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs uppercase text-slate-500">{['Número','Fecha','Responsable','Sistema','Confirmado','Diferencia','Resultado','Estado','Acciones'].map(x=><th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{history.map(a=>{const s=a.snapshot_resumen||{};return <tr key={a.id} className="border-t"><td className="p-2 font-bold">{a.numero_arqueo}</td><td>{date(a.fecha_operativa)}</td><td>{a.responsable?.nombre}</td><td>{money(s.total_sistema)}</td><td>{s.total_confirmado==null?'—':money(s.total_confirmado)}</td><td>{s.diferencia_total==null?'—':money(s.diferencia_total)}</td><td>{a.resultado_cierre||'—'}</td><td>{a.estado}</td><td className="flex gap-1 p-2"><button title="Ver detalle" onClick={()=>openDetail(a.id)} className="rounded border p-2"><Eye size={15}/></button><button title="Descargar PDF" onClick={async()=>downloadPdf(await getArqueoDetalle(a.id))} className="rounded border p-2"><Download size={15}/></button>{a.estado==='Cerrado'&&isAdmin&&<button title="Reabrir" onClick={async()=>{const r=await Swal.fire({title:'Reabrir arqueo',input:'textarea',inputLabel:'Motivo obligatorio',showCancelButton:true});if(r.isConfirmed&&r.value){try{await reopenArqueoPago(a.id,r.value);load()}catch(e){Swal.fire({icon:'error',title:'No se pudo reabrir',text:e.message})}}}} className="rounded border p-2"><Undo2 size={15}/></button>}</td></tr>})}</tbody></table>{!history.length&&<p className="py-14 text-center text-slate-500">No existen arqueos.</p>}</div>}
    {tab==='consolidado'&&<ConsolidadoFinanciero/>}
    <Modal open={Boolean(detail)} title={detail?.numero_arqueo||'Detalle histórico'} onClose={()=>setDetail(null)} size="wide">{detail&&<div className="grid gap-4"><div className="grid grid-cols-2 gap-2 md:grid-cols-4">{[['Fecha',date(detail.fecha_operativa)],['Responsable',detail.responsable?.nombre],['Resultado',detail.resultado_cierre],['Saldo dejado',money(detail.saldo_dejado_caja)]].map(([l,v])=><div key={l} className="rounded-lg bg-slate-50 p-3"><small>{l}</small><b className="block">{v}</b></div>)}</div><h3 className="font-black">Pagos congelados ({detail.movimientosSnapshot?.length||0})</h3><div className="max-h-40 overflow-auto">{detail.movimientosSnapshot?.map(r=><p key={r.id} className="border-t py-2 text-sm">{r.paciente_nombre_snapshot} · {r.concepto_snapshot} · {r.metodo_snapshot} · {money(r.monto_snapshot)}</p>)}</div><h3 className="font-black">Movimientos de caja congelados ({detail.movimientosCajaSnapshot?.length||0})</h3><div className="max-h-40 overflow-auto">{detail.movimientosCajaSnapshot?.map(r=><p key={r.id} className="border-t py-2 text-sm">{r.tipo_movimiento_snapshot} · {r.concepto_snapshot} · {r.metodo_snapshot} · {money(r.monto_snapshot)}</p>)}</div><div className="flex justify-end"><Button onClick={()=>downloadPdf(detail)}><Download size={16}/>Descargar PDF A4</Button></div></div>}</Modal>
  </section>;
}

export default Arqueos;
