import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, Banknote, CalendarDays, Clock3, CreditCard, Download, FileText, HeartPulse, Landmark, ReceiptText, TrendingDown, TrendingUp, UsersRound, WalletCards } from 'lucide-react';
import Button from '../../components/common/Button';
import Input from '../../components/common/Input';
import Loader from '../../components/common/Loader';
import { useAuth } from '../../context/AuthContext';
import { getArqueosConsolidado } from '../../services/planillaPagosService';
import { boliviaDate, formatBoliviaDateTime } from '../../utils/boliviaDateTime';
import { exportConsolidadoExcel } from '../../utils/exportConsolidadoFinanciero';
import { buildObligationPdfRows, obligationPdfHeaders, obligationPdfWidths, paginateRows, pdfPeriodLabel } from '../../utils/consolidadoPdf';
import logo from '../../assets/logos/logo.png';

const money = (value) => `Bs ${Number(value || 0).toLocaleString('es-BO', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const date = (value) => value ? formatBoliviaDateTime(`${value}T12:00:00-04:00`, { dateStyle: 'short' }) : '—';
const monthOptions = ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'].map((label,index)=>({value:String(index+1).padStart(2,'0'),label}));
const yearOptions = Array.from({length:23},(_,index)=>{const value=String(new Date().getFullYear()+2-index);return {value,label:value};});
const comparisonLabels = { pacientes_atendidos:'Pacientes atendidos', sesiones_realizadas:'Sesiones realizadas', total_cobrado:'Total cobrado', efectivo:'Efectivo', qr:'QR', transferencia:'Transferencia', tarjeta:'Tarjeta', otro:'Otro método', ingresos_extraordinarios:'Ingresos extraordinarios', total_ingresos_operativos:'Ingresos operativos', total_egresos_operativos:'Egresos operativos', resultado_neto_operativo:'Resultado neto operativo', pendiente_servicios_originados:'Pendiente originado en el período' };
const countMetrics = new Set(['pacientes_atendidos','sesiones_realizadas']);
const sessionLabel = (row) => row.numero_sesion
  ? `Sesión ${row.numero_sesion}-${row.total_sesiones || row.numero_sesion}`
  : String(row.servicio || 'Servicio').split(/\s+[—-]\s+/)[0];

function Metric({ icon: Icon, label, value, tone='teal', detail }) { const styles={teal:'border-teal-100 bg-teal-50 text-teal-700',green:'border-emerald-100 bg-emerald-50 text-emerald-700',rose:'border-rose-100 bg-rose-50 text-rose-700',amber:'border-amber-100 bg-amber-50 text-amber-700',sky:'border-sky-100 bg-sky-50 text-sky-700',violet:'border-violet-100 bg-violet-50 text-violet-700'};return <article className={`rounded-xl border p-3 ${styles[tone]}`}><div className="flex items-center justify-between gap-2"><span className="text-[10px] font-black uppercase tracking-wide">{label}</span><Icon size={17}/></div><strong className="mt-2 block text-xl text-slate-900">{value}</strong>{detail&&<small className="mt-1 block text-slate-500">{detail}</small>}</article>}
function Section({ title, subtitle, children }) { return <section className="rounded-xl border border-slate-200 bg-white p-4"><h3 className="font-black text-slate-900">{title}</h3>{subtitle&&<p className="mt-0.5 text-xs text-slate-500">{subtitle}</p>}<div className="mt-3">{children}</div></section> }

const downloadConsolidatedPdf = async (data, responsible) => {
  const { jsPDF } = await import('jspdf'); const pdf=new jsPDF({unit:'mm',format:'a4'});let y=18;
  const periodTitle={dia:'DIARIO',semana:'SEMANAL',mes:'MENSUAL',personalizado:'PERSONALIZADO'}[data.periodo.tipo]||data.periodo.tipo.toUpperCase();
  const availableBottom=()=>pdf.internal.pageSize.getHeight()-16;
  const rightEdge=()=>pdf.internal.pageSize.getWidth()-16;
  const nextPage=()=>{pdf.addPage();y=18};
  const line=(label,value)=>{if(y+7>availableBottom())nextPage();pdf.setFont('helvetica','normal');pdf.text(String(label),16,y);pdf.setFont('helvetica','bold');pdf.text(String(value),rightEdge(),y,{align:'right'});y+=7};
  const title=(text)=>{if(y+14>availableBottom())nextPage();y+=3;pdf.setFillColor(240,253,250);pdf.rect(14,y-5,pdf.internal.pageSize.getWidth()-28,9,'F');pdf.setTextColor(15,118,110);pdf.setFont('helvetica','bold');pdf.text(text,17,y+1);pdf.setTextColor(30,41,59);y+=10};
  const table=(heading,headers,rows,widths,periodText='')=>{pdf.setFontSize(7);const wrapped=(row)=>row.map((value,index)=>pdf.splitTextToSize(String(value??'—'),widths[index]-2));const height=(row)=>Math.max(7,...wrapped(row).map(lines=>lines.length*3.2+2));const pages=paginateRows(rows,height,160);pages.forEach((pageRows,pageIndex)=>{pdf.addPage('a4','landscape');y=16;pdf.setTextColor(15,118,110);pdf.setFont('helvetica','bold');pdf.setFontSize(15);pdf.text(heading,14,y);if(periodText){pdf.setTextColor(71,85,105);pdf.setFont('helvetica','normal');pdf.setFontSize(8);pdf.text(`Período: ${periodText}`,14,y+5)}y+=periodText?13:8;let x=12;pdf.setFillColor(199,249,240);pdf.rect(12,y-5,widths.reduce((a,b)=>a+b,0),8,'F');pdf.setTextColor(30,41,59);pdf.setFont('helvetica','bold');pdf.setFontSize(7);headers.forEach((header,index)=>{pdf.text(String(header),x+1,y,{maxWidth:widths[index]-2});x+=widths[index]});y+=6;pageRows.forEach(row=>{const cells=wrapped(row),rowHeight=height(row);x=12;pdf.setFont('helvetica','normal');cells.forEach((lines,index)=>{const state=index===headers.length-1?String(row[index]||'').toUpperCase():'';if(state==='CANCELADO')pdf.setTextColor(5,150,105);else if(state==='PENDIENTE')pdf.setTextColor(180,83,9);else if(state==='NO CANCELADO')pdf.setTextColor(190,18,60);else pdf.setTextColor(30,41,59);pdf.text(lines,x+1,y,{maxWidth:widths[index]-2});x+=widths[index]});pdf.setDrawColor(226,232,240);pdf.line(12,y+rowHeight-2,12+widths.reduce((a,b)=>a+b,0),y+rowHeight-2);y+=rowHeight})});return pages.length};
  const chart=(labels,values,heading)=>{pdf.addPage('a4','landscape');const canvas=document.createElement('canvas');canvas.width=1000;canvas.height=500;const ctx=canvas.getContext('2d'),max=Math.max(...values.map(Number),1);ctx.fillStyle='#fff';ctx.fillRect(0,0,1000,500);ctx.fillStyle='#0f172a';ctx.font='bold 34px Arial';ctx.textAlign='center';ctx.fillText(heading,500,45);const gap=820/Math.max(values.length,1);values.forEach((value,index)=>{const h=Number(value)/max*300,x=90+gap*index+gap*.2;ctx.fillStyle='#0f766e';ctx.fillRect(x,380-h,gap*.6,h);ctx.fillStyle='#334155';ctx.font='16px Arial';ctx.fillText(String(labels[index]),x+gap*.3,410)});pdf.addImage(canvas.toDataURL('image/png'),'PNG',25,25,245,145);y=180};
  try{const blob=await fetch(logo).then(response=>response.blob());const logoData=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob)});pdf.addImage(logoData,'PNG',166,8,27,18)}catch{/* El encabezado textual se conserva si el logo no puede cargarse. */}
  pdf.setTextColor(15,118,110);pdf.setFont('helvetica','bold');pdf.setFontSize(17);pdf.text('PHYSIO ACTIVE',16,y);y+=9;pdf.setTextColor(30,41,59);pdf.setFontSize(13);pdf.text(`CONSOLIDADO ${periodTitle}`,16,y);y+=8;pdf.setFontSize(9);line('Período',`${date(data.periodo.desde)} al ${date(data.periodo.hasta)}`);line('Fecha de generación',formatBoliviaDateTime(new Date().toISOString()));line('Generado por',responsible||'Administrador');
  title('ACTIVIDAD');line('Pacientes atendidos',data.actividad_clinica.pacientes_atendidos);line('Sesiones realizadas',data.actividad_clinica.sesiones_realizadas);
  title('COBROS');Object.entries({Total:data.cobros.total_cobrado,Efectivo:data.cobros.efectivo,QR:data.cobros.qr,Transferencia:data.cobros.transferencia,'QR + Transferencia':data.cobros.qr_transferencia_total,Tarjeta:data.cobros.tarjeta,Otro:data.cobros.otro}).forEach(([k,v])=>line(k,money(v)));
  title('DEUDA');line('Deuda vigente actual',money(data.deuda.deuda_vigente_actual));line('Pendiente originado en el período',money(data.deuda.deuda_originada_periodo));line('Pacientes con deuda',data.deuda.pacientes_con_deuda||0);
  title('INGRESOS, EGRESOS Y RESULTADO');line('Ingresos extraordinarios',money(data.caja.ingresos_extraordinarios));line('Ingresos operativos',money(data.resultado.total_ingresos_operativos));line('Egresos operativos',money(data.resultado.total_egresos_operativos));line('Resultado neto operativo',money(data.resultado.resultado_neto_operativo));
  const detailTitle=`ARQUEO ${periodTitle} — DETALLE DE COBROS`;table(detailTitle,obligationPdfHeaders,buildObligationPdfRows(data),obligationPdfWidths,pdfPeriodLabel(data.periodo));
  if(data.periodo.tipo==='mes'){title('SERVICIOS Y GASTOS');line('Ingresos fisioterapia',money(data.servicios.ingresos_fisioterapia));line('Ingresos otros servicios',money(data.servicios.ingresos_otros_servicios));data.gastos_por_categoria.filter(x=>x.monto>0).forEach(x=>line(x.categoria.replaceAll('_',' '),money(x.monto)))}
  if(data.periodo.tipo==='semana'){table('ARQUEO SEMANAL — RESUMEN POR DÍA',['Fecha','Pacientes','Sesiones','Cobrado','Efectivo','QR / Transf.','Tarjetas','Cuentas por cobrar','Gastos','Resultado'],(data.resumen_diario||[]).map(row=>[date(row.fecha),row.pacientes_atendidos,row.sesiones,money(row.total_cobrado),money(row.efectivo),money(row.qr_transferencia),money(row.tarjeta),money(row.deuda_generada),money(row.gastos),money(row.resultado_neto)]),[24,22,20,28,25,29,24,34,24,28]);chart((data.resumen_diario||[]).map(row=>date(row.fecha)),(data.resumen_diario||[]).map(row=>row.total_cobrado),'Ingresos diarios de la semana')}
  if(data.periodo.tipo==='mes')chart(['Efectivo','QR + Transferencia','Tarjetas','Otro'],[data.cobros.efectivo,data.cobros.qr_transferencia_total,data.cobros.tarjeta,data.cobros.otro],'Cobros por medio de pago');
  if((data.detalle_egresos||[]).length){title('DETALLE DE EGRESOS');data.detalle_egresos.forEach(row=>line(`${date(row.fecha)} · ${row.concepto} · ${row.categoria.replaceAll('_',' ')}`,money(row.monto)))}
  if(data.periodo.tipo!=='dia')table('CONTROL INDIVIDUAL POR PACIENTE',['Paciente','Documento','Sesiones','Total tratamiento','Pagado período','Pagado acumulado','Saldo pendiente'],(data.detalle_pacientes||[]).map(row=>[row.paciente,row.documento,row.sesiones_realizadas,money(row.total_tratamiento),money(row.pagado_periodo),money(row.pagado_acumulado),money(row.deuda_actual)]),[50,35,25,38,38,38,38]);
  if(data.periodo.tipo!=='dia'){title('COMPARACIÓN CON PERÍODO ANTERIOR');Object.entries(data.comparacion.metricas).filter(([key])=>['pacientes_atendidos','sesiones_realizadas','total_cobrado','total_ingresos_operativos','total_egresos_operativos','resultado_neto_operativo'].includes(key)).forEach(([key,value])=>line(comparisonLabels[key],`${countMetrics.has(key)?value.actual:money(value.actual)} | Anterior ${countMetrics.has(key)?value.anterior:money(value.anterior)} | ${value.etiqueta}`))}
  const pages=pdf.getNumberOfPages();for(let page=1;page<=pages;page+=1){pdf.setPage(page);const pageWidth=pdf.internal.pageSize.getWidth(),pageHeight=pdf.internal.pageSize.getHeight();pdf.setFontSize(8);pdf.setTextColor(100);pdf.text(`CONSOLIDADO ${periodTitle} · ${date(data.periodo.desde)} al ${date(data.periodo.hasta)}`,12,pageHeight-7);pdf.text(`Página ${page} de ${pages}`,pageWidth-12,pageHeight-7,{align:'right'});}
  pdf.save(`Consolidado_${data.periodo.tipo}_${data.periodo.desde}_${data.periodo.hasta}.pdf`);
};

export default function ConsolidadoFinanciero() {
  const { user }=useAuth();const today=boliviaDate();const [type,setType]=useState('dia');const [anchor,setAnchor]=useState(today);const [custom,setCustom]=useState({desde:today,hasta:today});const [data,setData]=useState(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  const query=useMemo(()=>type==='personalizado'?{tipo:type,...custom}:{tipo:type,fechaReferencia:anchor},[anchor,custom,type]);
  const load=useCallback(async()=>{if(type==='personalizado'&&custom.desde>custom.hasta){setError('La fecha inicial no puede ser posterior a la fecha final.');setData(null);return}setLoading(true);setError('');try{const response=await getArqueosConsolidado(query);setData({...response,detalle_cobros:(response.detalle_cobros||[]).map(row=>({...row,servicio:sessionLabel(row)}))})}catch(err){setData(null);setError(err.message||'No se pudo cargar el consolidado financiero.')}finally{setLoading(false)}},[custom.desde,custom.hasta,query,type]);
  useEffect(()=>{load()},[load]);
  useEffect(()=>{const refresh=()=>{if(document.visibilityState==='visible')load()};const timer=window.setInterval(refresh,15000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{window.clearInterval(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh)}},[load]);
  const c=data?.cobros||{};const clinic=data?.actividad_clinica||{};const cash=data?.caja||{};const result=data?.resultado||{};
  return <div className="grid gap-4"><header className="rounded-xl border border-teal-100 bg-gradient-to-r from-teal-50 via-white to-sky-50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black">Consolidado financiero</h2><p className="text-sm text-slate-600">Resumen operativo de cobros, atención, gastos y resultado por período.</p></div>{data&&<div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>downloadConsolidatedPdf(data,user?.nombre_mostrado||user?.nombre)}><Download size={16}/>Generar PDF</Button><Button variant="secondary" onClick={()=>exportConsolidadoExcel(data,user?.nombre_mostrado||user?.nombre)}><FileText size={16}/>Generar Excel</Button></div>}</div><div className="mt-4 rounded-xl border bg-white/80 p-3"><div className="flex flex-wrap gap-2">{[['dia','Diario'],['semana','Semanal'],['mes','Mensual']].map(([key,label])=><button type="button" key={key} aria-pressed={type===key} onClick={()=>setType(key)} className={`min-h-10 flex-1 rounded-lg px-4 text-sm font-black sm:flex-none ${type===key?'bg-teal-600 text-white':'bg-slate-50 text-slate-600'}`}>{label}</button>)}</div><div className="mt-3 flex flex-wrap items-end gap-3">{type==='dia'&&<Input compact label="Fecha" type="date" value={anchor} onChange={e=>setAnchor(e.target.value)}/>} {type==='semana'&&<Input compact label="Semana de referencia" type="date" value={anchor} onChange={e=>setAnchor(e.target.value)}/>} {type==='mes'&&<><Input compact label="Mes" value={anchor.slice(5,7)} options={monthOptions} onChange={e=>setAnchor(`${anchor.slice(0,4)}-${e.target.value}-01`)}/><Input compact label="Año" value={anchor.slice(0,4)} options={yearOptions} onChange={e=>setAnchor(`${e.target.value}-${anchor.slice(5,7)}-01`)}/></>}<Button onClick={load}>Consultar</Button>{data&&<span className="rounded-lg bg-teal-50 px-3 py-2 text-xs font-black text-teal-700">{date(data.periodo.desde)} — {date(data.periodo.hasta)}</span>}</div></div></header>
    {loading&&<div className="grid min-h-52 place-items-center"><Loader/></div>}{!loading&&error&&<div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-5 text-center text-rose-700"><b>No se pudo cargar el consolidado financiero.</b><p className="text-sm">{error}</p></div>}
    {!loading&&data&&<><div className={`rounded-xl border p-3 text-sm font-bold ${data.cierres_diarios.cantidad?'border-teal-200 bg-teal-50 text-teal-700':'border-amber-200 bg-amber-50 text-amber-700'}`}>{data.cierres_diarios.estado} · {data.cierres_diarios.cantidad} cierre(s) · {data.cierres_diarios.dias_con_actividad} día(s) con actividad</div>{!data.tiene_actividad&&<div className="rounded-xl bg-slate-50 py-10 text-center text-slate-500">No existen movimientos ni sesiones registradas para este período.</div>}
      <Section title="Actividad clínica" subtitle="Pacientes atendidos se calcula desde sesiones asistidas, no desde pagadores."><div className="grid grid-cols-2 gap-3"><Metric icon={UsersRound} label="Pacientes atendidos" value={clinic.pacientes_atendidos||0}/><Metric icon={HeartPulse} label="Sesiones realizadas" value={clinic.sesiones_realizadas||0} tone="sky"/></div></Section>
      <Section title="Cobros de pacientes"><div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6"><Metric icon={Banknote} label="Total cobrado" value={money(c.total_cobrado)} tone="green"/><Metric icon={WalletCards} label="Efectivo" value={money(c.efectivo)}/><Metric icon={CreditCard} label="QR" value={money(c.qr)} tone="violet"/><Metric icon={CreditCard} label="Transferencia" value={money(c.transferencia)} tone="sky"/><Metric icon={CreditCard} label="Tarjeta" value={money(c.tarjeta)} tone="rose"/><Metric icon={ReceiptText} label="Otro" value={money(c.otro)}/></div></Section>
      <div className="grid gap-4 lg:grid-cols-2"><Section title="Ingresos por servicios" subtitle={data.servicios.clasificacion}><div className="grid grid-cols-2 gap-3"><Metric icon={Activity} label="Fisioterapia" value={money(data.servicios.ingresos_fisioterapia)} tone="green"/><Metric icon={FileText} label="Otros servicios" value={money(data.servicios.ingresos_otros_servicios)} tone="sky"/></div></Section><Section title="Deuda" subtitle="La deuda vigente es actual y se actualiza con cada pago; nunca se cuenta como ingreso."><div className="grid grid-cols-2 gap-3 md:grid-cols-3"><Metric icon={Clock3} label="Deuda vigente actual" value={money(data.deuda.deuda_vigente_actual)} tone="rose"/><Metric icon={CalendarDays} label="Pendiente originado en el período" value={money(data.deuda.deuda_originada_periodo)} tone="amber"/><Metric icon={UsersRound} label="Pacientes con deuda" value={data.deuda.pacientes_con_deuda||0} tone="violet"/></div></Section></div>
      <Section title="Ingresos, egresos y resultado"><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Metric icon={Banknote} label="Cobros pacientes" value={money(c.total_cobrado)} tone="green"/><Metric icon={TrendingUp} label="Ingresos extraordinarios" value={money(cash.ingresos_extraordinarios)} tone="sky"/><Metric icon={WalletCards} label="Ingresos operativos" value={money(result.total_ingresos_operativos)} tone="teal"/><Metric icon={TrendingDown} label="Egresos operativos" value={money(result.total_egresos_operativos)} tone="rose"/><Metric icon={Landmark} label="Gastos administrativos" value={money(data.gastos_resumen.administrativos)} tone="amber"/><Metric icon={Activity} label="Gastos de insumos" value={money(data.gastos_resumen.insumos)} tone="violet"/><Metric icon={ReceiptText} label="Otros egresos" value={money(data.gastos_resumen.otros)} tone="rose"/><Metric icon={TrendingUp} label="Resultado neto operativo" value={money(result.resultado_neto_operativo)} tone={result.resultado_neto_operativo>=0?'green':'rose'}/></div><p className="mt-3 text-xs text-slate-500">Aportes, retiros y ajustes se muestran separados y no alteran el resultado operativo: aportes {money(cash.aportes)} · retiros {money(cash.retiros)} · ajustes +{money(cash.ajustes_positivos)} / −{money(cash.ajustes_negativos)}.</p></Section>
      {type==='dia'&&<Section title="Arqueo del día" subtitle="Consulta informativa: el cierre se gestiona únicamente desde Arqueo actual.">{!data.arqueo_diario?.existe?<div className="rounded-xl border border-amber-200 bg-amber-50 p-4 font-bold text-amber-700">{data.tiene_actividad?'Este día tiene actividad financiera pero aún no posee un cierre diario.':'Sin cierre diario'}</div>:<><div className={`mb-3 rounded-lg p-3 font-black ${data.arqueo_diario.cerrado?'bg-teal-50 text-teal-700':'bg-amber-50 text-amber-700'}`}>{data.arqueo_diario.estado}</div><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Metric icon={UsersRound} label="Responsable" value={data.arqueo_diario.responsable}/><Metric icon={WalletCards} label="Saldo inicial" value={money(data.arqueo_diario.saldo_inicial)} tone="sky"/><Metric icon={Banknote} label="Efectivo sistema" value={money(data.arqueo_diario.sistema.efectivo)} tone="teal"/><Metric icon={Banknote} label="Efectivo confirmado" value={money(data.arqueo_diario.confirmado.efectivo)} tone="green"/><Metric icon={CreditCard} label="QR sistema / confirmado" value={`${money(data.arqueo_diario.sistema.qr)} / ${money(data.arqueo_diario.confirmado.qr)}`} tone="violet"/><Metric icon={CreditCard} label="Transferencia sistema / confirmado" value={`${money(data.arqueo_diario.sistema.transferencia)} / ${money(data.arqueo_diario.confirmado.transferencia)}`} tone="sky"/><Metric icon={CreditCard} label="Tarjeta sistema / confirmado" value={`${money(data.arqueo_diario.sistema.tarjeta)} / ${money(data.arqueo_diario.confirmado.tarjeta)}`} tone="amber"/><Metric icon={ReceiptText} label="Otro sistema / confirmado" value={`${money(data.arqueo_diario.sistema.otro)} / ${money(data.arqueo_diario.confirmado.otro)}`}/><Metric icon={TrendingDown} label="Diferencia total" value={money(data.arqueo_diario.diferencias.total)} tone="rose"/><Metric icon={Banknote} label="Monto retirado" value={money(data.arqueo_diario.monto_retirado)} tone="amber"/><Metric icon={WalletCards} label="Saldo dejado en caja" value={money(data.arqueo_diario.saldo_dejado_caja)} tone="green"/></div></>}</Section>}
      {type==='dia'&&<Section title="Detalle de pacientes y cobros" subtitle="Pagos reales registrados durante el día seleccionado."><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-sm"><thead className="text-left text-[10px] uppercase text-slate-500"><tr>{['Hora','Paciente','Documento','Profesional','Cobrado','Método','Recibo','Saldo','Estado'].map(x=><th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{data.detalle_cobros.map(row=><tr key={row.id} className="border-t"><td className="p-2">{String(row.hora||'').slice(0,5)}</td><td className="p-2 font-bold">{row.paciente}</td><td className="p-2">{row.documento}</td><td className="p-2">{row.profesional}</td><td className="p-2 text-right font-bold whitespace-nowrap">{money(row.monto)}</td><td className="p-2">{row.metodo}</td><td className="p-2">{row.numero_recibo}</td><td className="p-2 text-right whitespace-nowrap">{money(row.deuda_actual)}</td><td className="p-2"><span className={`rounded-full px-2 py-1 text-xs font-bold ${row.estado_deuda==='Sin deuda'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{row.estado_deuda}</span></td></tr>)}</tbody></table>{!data.detalle_cobros.length&&<p className="py-8 text-center text-slate-500">No existen cobros registrados durante este día.</p>}</div></Section>}
      {type!=='dia'&&<Section title="Resumen por día"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="text-left text-[10px] uppercase text-slate-500"><tr>{['Fecha','Pacientes','Sesiones','Cobrado','Efectivo','QR / transferencia','Tarjeta','Deuda generada','Gastos','Resultado'].map(x=><th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{data.resumen_diario.map(row=><tr key={row.fecha} className="border-t"><td className="p-2 font-bold">{date(row.fecha)}</td><td>{row.pacientes_atendidos}</td><td>{row.sesiones}</td><td>{money(row.total_cobrado)}</td><td>{money(row.efectivo)}</td><td>{money(row.qr_transferencia)}</td><td>{money(row.tarjeta)}</td><td>{money(row.deuda_generada)}</td><td>{money(row.gastos)}</td><td className="font-bold">{money(row.resultado_neto)}</td></tr>)}</tbody></table></div></Section>}
      {type!=='dia'&&<Section title="Control individual por paciente" subtitle={`Pagado durante el período ${date(data.periodo.desde)} al ${date(data.periodo.hasta)} y saldo acumulado actual.`}><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="text-left text-[10px] uppercase text-slate-500"><tr>{['Paciente','Documento','Sesiones','Total tratamiento','Pagado período','Pagado acumulado','Deuda actual'].map(x=><th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{data.detalle_pacientes.map(row=><tr key={row.paciente_id} className="border-t"><td className="p-2 font-bold">{row.paciente}</td><td>{row.documento}</td><td>{row.sesiones_realizadas}</td><td>{money(row.total_tratamiento)}</td><td className="text-emerald-700">{money(row.pagado_periodo)}</td><td>{money(row.pagado_acumulado)}</td><td className="font-bold text-rose-700">{money(row.deuda_actual)}</td></tr>)}</tbody></table></div></Section>}
      <Section title="Detalle de egresos"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-[10px] uppercase text-slate-500"><tr><th className="p-2">Fecha</th><th>Concepto</th><th>Categoría</th><th>Método</th><th className="text-right">Monto</th></tr></thead><tbody>{data.detalle_egresos.map(row=><tr key={row.id} className="border-t"><td className="p-2">{date(row.fecha)}</td><td>{row.concepto}</td><td>{row.categoria.replaceAll('_',' ')}</td><td>{row.metodo}</td><td className="text-right font-bold">{money(row.monto)}</td></tr>)}</tbody></table>{!data.detalle_egresos.length&&<p className="py-8 text-center text-slate-500">No existen egresos registrados en este período.</p>}</div></Section>
      <div className="grid gap-4 lg:grid-cols-2"><Section title="Gastos por categoría"><div className="grid gap-2">{data.gastos_por_categoria.map(row=><div key={row.categoria}><div className="flex justify-between text-sm"><b>{row.categoria.replaceAll('_',' ')}</b><span>{money(row.monto)} · {row.porcentaje.toFixed(2)}%</span></div><div className="mt-1 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-rose-400" style={{width:`${Math.min(row.porcentaje,100)}%`}}/></div></div>)}</div></Section>
        <Section title="Comparación con período anterior" subtitle={`${date(data.comparacion.periodo_anterior.desde)} — ${date(data.comparacion.periodo_anterior.hasta)}`}><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="text-left text-[10px] uppercase text-slate-500"><tr><th className="py-2">Métrica</th><th>Actual</th><th>Anterior</th><th>Variación</th></tr></thead><tbody>{Object.entries(data.comparacion.metricas).map(([key,value])=><tr key={key} className="border-t"><td className="py-2 font-bold">{comparisonLabels[key]||key}</td><td>{countMetrics.has(key)?value.actual:money(value.actual)}</td><td>{countMetrics.has(key)?value.anterior:money(value.anterior)}</td><td className="font-bold text-slate-700">{value.direccion==='sube'?'↑ ':value.direccion==='baja'?'↓ ':''}{value.etiqueta}</td></tr>)}</tbody></table></div></Section></div>
    </>}
  </div>;
}
