import { useEffect, useState } from 'react';
import { Banknote, CalendarCheck2, CalendarDays, CheckCircle2, Clock3, CreditCard, FileText, History, ReceiptText, Stethoscope, UserRound, WalletCards } from 'lucide-react';
import Button from '../../components/common/Button';
import Loader from '../../components/common/Loader';
import Modal from '../../components/common/Modal';
import { getResumenFinancieroPaciente } from '../../services/planillaPagosService';
import { formatBoliviaDateTime } from '../../utils/boliviaDateTime';

const money = (value) => `${Number(value || 0).toLocaleString('es-BO', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} Bs`;
const date = (value) => value ? formatBoliviaDateTime(`${value}T12:00:00-04:00`, { dateStyle: 'short' }) : 'Sin fecha';
const typeLabel = (type) => type === 'DEUDA_HISTORIA' ? 'Pago de deuda' : type === 'ESPECIFICO' ? 'Pago específico' : 'Pago histórico';
const stateTone = { Pagado: 'bg-emerald-50 text-emerald-700 border-emerald-200', Parcial: 'bg-amber-50 text-amber-700 border-amber-200', Pendiente: 'bg-rose-50 text-rose-700 border-rose-200', Exonerado: 'bg-sky-50 text-sky-700 border-sky-200', Anulado: 'bg-slate-100 text-slate-600 border-slate-200', 'Saldo a favor': 'bg-violet-50 text-violet-700 border-violet-200' };

function Metric({ icon: Icon, label, value, tone = 'teal' }) {
  const styles = { teal: 'border-teal-100 bg-teal-50 text-teal-700', green: 'border-emerald-100 bg-emerald-50 text-emerald-700', amber: 'border-amber-100 bg-amber-50 text-amber-700', rose: 'border-rose-100 bg-rose-50 text-rose-700', sky: 'border-sky-100 bg-sky-50 text-sky-700', violet: 'border-violet-100 bg-violet-50 text-violet-700' };
  return <article className={`rounded-xl border p-3 ${styles[tone]}`}><div className="flex items-center justify-between gap-2"><span className="text-[10px] font-black uppercase tracking-wide">{label}</span><Icon size={17}/></div><strong className="mt-2 block text-xl text-slate-900">{value}</strong></article>;
}

function ConceptCard({ row, showHistory }) {
  return <article className="rounded-xl border border-slate-200 p-3"><div className="flex items-start justify-between gap-2"><div><b className="text-sm">{row.sesion ? `Sesión ${row.sesion.numero_sesion}` : row.tipo}</b><span className="block text-xs text-slate-500">{date(row.fecha)}{showHistory ? ` · Historia ${row.historia_clinica_id || 'Sin historia'}` : ''}</span></div><span className={`rounded-full border px-2 py-1 text-[10px] font-black ${stateTone[row.estado] || stateTone.Pendiente}`}>{row.estado}</span></div><p className="mt-2 text-sm text-slate-600">{row.descripcion}</p><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><span>Esperado<b className="block">{money(row.esperado)}</b></span><span>Pagado<b className="block text-emerald-700">{money(row.pagado)}</b></span><span>Saldo<b className="block text-rose-700">{money(row.saldo)}</b></span></div></article>;
}

export default function ResumenFinancieroPacienteModal({ open, pacienteId, historiaIdInicial, onClose, onOpenReceipt }) {
  const [historyId, setHistoryId] = useState(historiaIdInicial ? String(historiaIdInicial) : '');
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  useEffect(() => { if (open) setHistoryId(historiaIdInicial ? String(historiaIdInicial) : ''); }, [historiaIdInicial, open]);
  useEffect(() => {
    if (!open || !pacienteId) return undefined;
    let active = true; setLoading(true); setError(''); setData(null);
    getResumenFinancieroPaciente(pacienteId, historyId || undefined).then((result) => { if (active) setData(result); }).catch((err) => { if (active) setError(err.message || 'No se pudo cargar el resumen financiero.'); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [historyId, open, pacienteId]);
  const summary = data?.resumen || {};
  const showHistory = !historyId;
  return <Modal open={open} title="Resumen financiero del paciente" subtitle="Resumen de sesiones, pagos y saldo del tratamiento." onClose={onClose} size="planilla" closeOnEscape>
    <div className="min-h-0 flex-1 overflow-y-auto p-4 sm:p-5">
      {loading && <div className="grid min-h-64 place-items-center"><Loader/></div>}
      {!loading && error && <div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-5 text-center text-rose-700"><b>No se pudo cargar el resumen</b><p className="mt-1 text-sm">{error}</p></div>}
      {!loading && !error && data && <div className="grid gap-5">
        <section className="rounded-2xl border border-teal-100 bg-gradient-to-r from-teal-50 via-white to-sky-50 p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex min-w-0 items-center gap-3"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-teal-600 text-white"><UserRound size={24}/></span><div className="min-w-0"><h3 className="truncate text-lg font-black text-slate-900">{data.paciente.nombre}</h3><p className="text-sm text-slate-600">{data.paciente.tipo_documento || 'Documento'}: {data.paciente.numero_documento || 'No registrado'} · Tel: {data.paciente.telefono || 'No registrado'}</p></div></div><label className="grid min-w-[250px] gap-1 text-xs font-black text-slate-700"><span>Historia clínica</span><select aria-label="Historia clínica" className="min-h-10 rounded-lg border-slate-200 bg-white text-sm" value={historyId} onChange={(event)=>setHistoryId(event.target.value)}><option value="">Todas las historias</option>{data.historias_disponibles.map((history)=><option key={history.id} value={history.id}>Historia {date(history.fecha_evaluacion)} — {history.diagnostico_medico || 'Sin diagnóstico'}</option>)}</select></label></div></section>
        <section><h3 className="mb-2 text-sm font-black text-slate-800">Resumen general</h3><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Stethoscope} label="Sesiones realizadas" value={summary.sesiones_realizadas || 0}/><Metric icon={FileText} label="Total esperado" value={money(summary.total_esperado)} tone="sky"/><Metric icon={CheckCircle2} label="Pagado total" value={money(summary.pagado_total)} tone="green"/><Metric icon={Clock3} label="Saldo pendiente" value={money(summary.saldo_pendiente)} tone="rose"/></div></section>
        <section><h3 className="mb-2 text-sm font-black text-slate-800">Pagos por período</h3><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={CalendarCheck2} label="Pagado hoy" value={money(summary.pagado_hoy)} tone="green"/><Metric icon={CalendarDays} label="Pagado esta semana" value={money(summary.pagado_semana)} tone="teal"/><Metric icon={History} label="Pagado este mes" value={money(summary.pagado_mes)} tone="violet"/><Metric icon={WalletCards} label="Total histórico" value={money(summary.pagado_total)} tone="amber"/></div><p className="mt-2 text-xs text-slate-500">Hoy: {date(data.periodos.hoy)} · Semana: {date(data.periodos.semana_inicio)} al {date(data.periodos.semana_fin)} · Mes: {date(data.periodos.mes_inicio)} al {date(data.periodos.mes_fin)}</p></section>
        <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-xl border border-slate-200 p-4"><h3 className="flex items-center gap-2 font-black"><ReceiptText size={18} className="text-teal-700"/>Último pago recibido</h3>{data.ultimo_pago?<div className="mt-3 grid grid-cols-2 gap-3 text-sm"><span>Tipo<b className="block">{typeLabel(data.ultimo_pago.tipo)}</b></span><span>Monto total<b className="block text-emerald-700">{money(data.ultimo_pago.monto)}</b></span><span>Fecha y hora<b className="block">{date(data.ultimo_pago.fecha)} {String(data.ultimo_pago.hora||'').slice(0,5)}</b></span><span>Método<b className="block">{data.ultimo_pago.metodo}</b></span><span>Recibo<b className="block break-all">{data.ultimo_pago.numero_recibo || 'Sin recibo'}</b></span><span>Recibido por<b className="block">{data.ultimo_pago.recibido_por?.nombre || 'Sin registrar'}</b></span>{data.ultimo_pago.numero_comprobante&&<span className="col-span-2">Comprobante<b className="block">{data.ultimo_pago.numero_comprobante}</b></span>}<div className="col-span-2 flex flex-wrap gap-2">{data.ultimo_pago.numero_recibo&&<Button variant="secondary" onClick={()=>onOpenReceipt?.(data.ultimo_pago)}><ReceiptText size={15}/>Ver recibo</Button>}{data.ultimo_pago.archivo_comprobante&&<a href={data.ultimo_pago.archivo_comprobante} target="_blank" rel="noreferrer" className="inline-flex min-h-10 items-center rounded-lg border px-4 text-sm font-bold text-teal-700">Ver comprobante</a>}</div></div>:<p className="mt-4 text-sm text-slate-500">No existen pagos activos en la selección.</p>}</section>
          <section className="rounded-xl border border-slate-200 p-4"><h3 className="flex items-center gap-2 font-black"><CreditCard size={18} className="text-teal-700"/>Pagos por método</h3><div className="mt-3 grid gap-3">{data.metodos.map((method)=><div key={method.metodo}><div className="mb-1 flex justify-between text-sm"><b>{method.metodo}</b><span>{money(method.monto)} · {method.porcentaje.toFixed(2)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-teal-500" style={{width:`${Math.min(method.porcentaje,100)}%`}}/></div></div>)}</div><div className="mt-3 flex justify-between border-t pt-3 font-black"><span>Total</span><span>{money(summary.pagado_total)}</span></div></section></div>
        <section><div className="mb-2 flex items-center justify-between"><h3 className="font-black">Conceptos y sesiones asociados</h3><span className="text-xs text-slate-500">{data.conceptos.length} concepto(s)</span></div>{data.conceptos.length?<><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr>{showHistory&&<th className="p-3">Historia</th>}<th className="p-3">Sesión</th><th className="p-3">Fecha</th><th className="p-3">Descripción</th><th className="p-3">Esperado</th><th className="p-3">Pagado</th><th className="p-3">Saldo</th><th className="p-3">Estado</th></tr></thead><tbody>{data.conceptos.map((row)=><tr key={row.id} className="border-t">{showHistory&&<td className="p-3">{row.historia_clinica_id ? `Historia ${row.historia_clinica_id}` : 'Sin historia'}</td>}<td className="p-3 font-bold">{row.sesion ? `Sesión ${row.sesion.numero_sesion}` : row.tipo}</td><td className="p-3">{date(row.fecha)}</td><td className="max-w-64 p-3">{row.descripcion}</td><td className="p-3">{money(row.esperado)}</td><td className="p-3 text-emerald-700">{money(row.pagado)}</td><td className="p-3 text-rose-700">{money(row.saldo)}</td><td className="p-3"><span className={`rounded-full border px-2 py-1 text-[10px] font-black ${stateTone[row.estado]||stateTone.Pendiente}`}>{row.estado}</span></td></tr>)}</tbody><tfoot className="border-t-2 font-black"><tr>{showHistory&&<td/>}<td className="p-3" colSpan="3">TOTALES</td><td className="p-3">{money(summary.total_esperado)}</td><td className="p-3 text-emerald-700">{money(summary.pagado_total)}</td><td className="p-3 text-rose-700">{money(summary.saldo_pendiente)}</td><td/></tr></tfoot></table></div><div className="grid gap-3 md:hidden">{data.conceptos.map((row)=><ConceptCard key={row.id} row={row} showHistory={showHistory}/>)}</div></>:<div className="rounded-xl bg-slate-50 py-10 text-center text-sm text-slate-500">No existen conceptos asociados a la selección.</div>}</section>
      </div>}
    </div>
    <div className="flex shrink-0 justify-end border-t p-3"><Button variant="secondary" onClick={onClose}>Cerrar</Button></div>
  </Modal>;
}
