import { useState } from 'react';
import Button from '../../components/common/Button';
import Modal from '../../components/common/Modal';
import { getReceptionReplyConfiguration, listReceptionReplies, previewReceptionReply, confirmReceptionReply, cancelReceptionReply, retryReceptionReply } from '../../services/whatsappReceptionService';

export default function ReceptionReply({ detail, user, onError }) {
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [config, setConfig] = useState(null); const [message, setMessage] = useState(''); const [preview, setPreview] = useState(null); const [history, setHistory] = useState([]);
  if (!detail || detail.estado !== 'EN_ATENCION' || (user?.rol !== 'admin' && Number(detail.responsable_id) !== Number(user?.id))) return null;
  const launch = async () => { setBusy(true); try { const [nextConfig, nextHistory] = await Promise.all([getReceptionReplyConfiguration(detail.id), listReceptionReplies(detail.id)]); setConfig(nextConfig); setHistory(nextHistory); setOpen(true); } catch (e) { onError(e.response?.data?.message || 'No se pudo preparar la respuesta.'); } finally { setBusy(false); } };
  const prepare = async () => { setBusy(true); try { setPreview(await previewReceptionReply(detail.id, message)); } catch (e) { onError(e.response?.data?.message || 'No se pudo crear la vista previa.'); } finally { setBusy(false); } };
  const run = async (operation) => { setBusy(true); try { const saved = await operation(); setHistory((items) => [saved, ...items.filter((item) => item.id !== saved.id)]); setPreview(null); setMessage(''); } catch (e) { onError(e.response?.data?.message || 'No se pudo procesar la respuesta.'); } finally { setBusy(false); } };
  return <><div className="fixed bottom-6 right-6 z-30"><Button variant="secondary" disabled={busy} onClick={launch}>Responder por WhatsApp</Button></div><Modal open={open} title="Responder por WhatsApp" subtitle="Vista previa y confirmación obligatorias" onClose={() => setOpen(false)} size="lg"><div className="grid gap-4">{config && !config.enabled && <p role="alert" className="rounded-lg bg-amber-50 p-3 text-sm font-bold text-amber-800">Los envíos manuales están deshabilitados. Puedes preparar una vista previa, pero no enviarla.</p>}{config && !config.ventana?.abierta && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">La ventana está cerrada o no pudo determinarse. Se requiere una plantilla aprobada; no hay ninguna configurada.</p>}{!preview && <><textarea aria-label="Mensaje de WhatsApp" value={message} onChange={(e) => setMessage(e.target.value)} maxLength={1000} disabled={!config?.ventana?.abierta} className="min-h-32 rounded-lg border-slate-200" placeholder="Respuesta administrativa"/><p className="text-right text-xs text-slate-500">{message.length}/1000</p><Button disabled={busy || !message.trim() || !config?.ventana?.abierta} onClick={prepare}>Previsualizar</Button></>}{preview && <div className="grid gap-3 rounded-xl border p-4"><p className="text-xs font-bold uppercase text-slate-500">Se enviará a {preview.telefono}</p><p className="whitespace-pre-wrap">{preview.mensaje}</p><p className="text-xs text-slate-500">Caduca a las {new Date(preview.expira_en).toLocaleTimeString('es-BO')}.</p><div className="flex gap-2"><Button disabled={busy || !config?.enabled} onClick={() => run(() => confirmReceptionReply(detail.id, preview.id))}>Confirmar y enviar</Button><Button variant="secondary" onClick={() => run(() => cancelReceptionReply(detail.id, preview.id))}>Cancelar</Button></div></div>}{history.length > 0 && <div><h3 className="font-bold">Historial técnico</h3>{history.map((item) => <div key={item.id} className="mt-2 rounded-lg bg-slate-50 p-3 text-sm"><b>{item.estado}</b> · {new Date(item.created_at).toLocaleString('es-BO')}{item.estado === 'REINTENTO' && <Button className="ml-2" variant="secondary" onClick={() => run(() => retryReceptionReply(detail.id, item.id))}>Reintentar</Button>}</div>)}</div>}</div></Modal></>;
}
