import { useCallback, useEffect, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Inbox, Eye, Hand, RefreshCw, CheckCircle2, Lock, MessageSquarePlus } from 'lucide-react';
import Button from '../../components/common/Button';
import Loader from '../../components/common/Loader';
import Modal from '../../components/common/Modal';
import Pagination from '../../components/common/Pagination';
import { useAuth } from '../../context/AuthContext';
import { listReceptionReferrals, getReceptionReferral, takeReceptionReferral, changeReceptionPriority, addReceptionObservation, resolveReceptionReferral, closeReceptionReferral } from '../../services/whatsappReceptionService';
import ReceptionReply from './ReceptionReply';

const labels = { CONSULTA_GENERAL: 'Consulta general', REGISTRO_PACIENTE: 'Registro de paciente', RECORDATORIO_CITA: 'Ayuda con cita', AYUDA_REPROGRAMACION: 'Ayuda para reprogramar', ERROR_DE_DATOS: 'Revisión de datos', PENDIENTE: 'Pendiente', EN_ATENCION: 'En atención', RESUELTA: 'Resuelta', CERRADA: 'Cerrada', CANCELADA: 'Cancelada' };
const initial = { estado: '', tipo: '', prioridad: '', buscar: '', page: 1, limit: 10 };
const badge = (value) => `rounded-full px-2.5 py-1 text-xs font-black ${value === 'URGENTE' || value === 'ALTA' ? 'bg-red-50 text-red-700' : value === 'PENDIENTE' ? 'bg-amber-50 text-amber-700' : value === 'EN_ATENCION' ? 'bg-blue-50 text-blue-700' : 'bg-emerald-50 text-emerald-700'}`;

export default function WhatsappReception() {
  const { user } = useAuth(); const location = useLocation(); const navigate = useNavigate(); const [filters, setFilters] = useState(initial); const [result, setResult] = useState({ data: [], pagination: {} }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [detail, setDetail] = useState(null); const [text, setText] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { setResult(await listReceptionReferrals(filters)); } catch (e) { setError(e.response?.data?.message || 'No se pudo cargar la bandeja.'); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { void load(); const refresh = () => void load(); const interval = window.setInterval(refresh, 30000); window.addEventListener('reception:updated', refresh); window.addEventListener('focus', refresh); return () => { window.clearInterval(interval); window.removeEventListener('reception:updated', refresh); window.removeEventListener('focus', refresh); }; }, [load]);
  const open = async (id) => { setBusy(true); try { setDetail(await getReceptionReferral(id)); setText(''); } catch (e) { setError(e.response?.data?.message || 'No se pudo abrir la solicitud.'); } finally { setBusy(false); } };
  useEffect(() => { if (location.state?.derivacionId) { void open(location.state.derivacionId); navigate(location.pathname, { replace: true, state: null }); } }, [location.state?.derivacionId]);
  const run = async (operation) => { setBusy(true); setError(''); try { const updated = await operation(); setDetail(updated); setText(''); await load(); window.dispatchEvent(new Event('reception:updated')); } catch (e) { setError(e.response?.data?.message || 'No se pudo completar la acción.'); } finally { setBusy(false); } };
  const set = (key, value) => setFilters((current) => ({ ...current, [key]: value, page: key === 'page' ? value : 1 }));
  return <div className="page-stack">
    {loading && <Loader />}
    <section className="hero-panel"><div><p className="eyebrow">WhatsApp</p><h1 className="mt-1 text-2xl font-black md:text-3xl">Solicitudes de recepción</h1><p className="mt-1 text-sm text-slate-500">Atención administrativa derivada por el asistente.</p></div><Inbox size={38} className="text-brand-700" /></section>
    <section className="content-card p-4 md:p-5">
      <div className="grid gap-3 md:grid-cols-5"><input aria-label="Buscar" value={filters.buscar} onChange={(e) => set('buscar', e.target.value)} placeholder="Nombre o teléfono" className="rounded-lg border-slate-200 text-sm" />{[['estado',['PENDIENTE','EN_ATENCION','RESUELTA','CERRADA','CANCELADA']],['tipo',['CONSULTA_GENERAL','REGISTRO_PACIENTE','RECORDATORIO_CITA','AYUDA_REPROGRAMACION','ERROR_DE_DATOS']],['prioridad',['URGENTE','ALTA','NORMAL','BAJA']]].map(([key, values]) => <select aria-label={key} key={key} value={filters[key]} onChange={(e) => set(key,e.target.value)} className="rounded-lg border-slate-200 text-sm"><option value="">{key === 'estado' ? 'Solicitudes activas' : `Todos: ${key}`}</option>{values.map(v=><option key={v} value={v}>{labels[v]||v}</option>)}</select>)}<Button variant="secondary" onClick={load}><RefreshCw size={16}/>Actualizar</Button></div>
      {error && <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm font-bold text-red-700">{error}</p>}
      <div className="mt-4 hidden overflow-x-auto rounded-xl border border-slate-200 md:block"><table className="min-w-full"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr>{['Tipo','Contacto','Teléfono','Estado','Prioridad','Creada','Responsable','Acciones'].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody className="divide-y">{result.data.map(item=><tr key={item.id}><td className="p-3 text-sm font-bold">{labels[item.tipo]}</td><td className="p-3 text-sm">{item.contacto}</td><td className="p-3 text-sm">{item.telefono}</td><td className="p-3"><span className={badge(item.estado)}>{labels[item.estado]}</span></td><td className="p-3"><span className={badge(item.prioridad)}>{item.prioridad}</span></td><td className="p-3 text-sm">{new Date(item.created_at).toLocaleString('es-BO')}</td><td className="p-3 text-sm">{item.responsable||'Sin asignar'}</td><td className="p-3"><Button variant="secondary" onClick={()=>open(item.id)}><Eye size={15}/>Ver</Button></td></tr>)}</tbody></table></div>
      <div className="mt-4 grid gap-3 md:hidden">{result.data.map(item=><article key={item.id} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between gap-2"><strong>{labels[item.tipo]}</strong><span className={badge(item.estado)}>{labels[item.estado]}</span></div><p className="mt-2 text-sm">{item.contacto} · {item.telefono}</p><p className="mt-1 text-xs text-slate-500">{new Date(item.created_at).toLocaleString('es-BO')}</p><Button className="mt-3 w-full" variant="secondary" onClick={()=>open(item.id)}><Eye size={15}/>Ver detalle</Button></article>)}</div>
      {!loading&&!result.data.length&&<div className="py-14 text-center text-slate-500"><Inbox className="mx-auto text-slate-300"/><p className="mt-3 font-bold">No hay solicitudes pendientes de recepción.</p><p className="text-sm">Las nuevas derivaciones de WhatsApp aparecerán aquí.</p></div>}
      <Pagination total={result.pagination.total||0} page={result.pagination.page||1} pageSize={result.pagination.limit||10} onPageChange={(v)=>set('page',v)} onPageSizeChange={(v)=>set('limit',v)}/>
    </section>
    <Modal open={Boolean(detail)} title="Detalle de solicitud" subtitle={detail&&labels[detail.tipo]} onClose={()=>setDetail(null)} size="lg"><>{busy&&<Loader/>}{detail&&<div className="grid gap-4"><div className="grid gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-2"><p><b>Contacto:</b> {detail.contacto}</p><p><b>Teléfono:</b> {detail.telefono}</p><p><b>Estado:</b> {labels[detail.estado]}</p><p><b>Responsable:</b> {detail.responsable||'Sin asignar'}</p>{detail.cita&&<p><b>Cita:</b> {detail.cita.fecha} · {detail.cita.hora_inicio}{detail.cita.hora_fin&&` a ${detail.cita.hora_fin}`}</p>}</div>{detail.solicitud&&<div className="grid gap-3 rounded-xl border border-teal-100 bg-teal-50/60 p-4 sm:grid-cols-2"><p><b>Nombre:</b> {detail.solicitud.nombre||detail.contacto}</p><p><b>Fecha solicitada:</b> {detail.solicitud.fecha||'Sin fecha'}</p><p><b>Horario:</b> {detail.solicitud.hora_inicio||'Sin horario'}{detail.solicitud.hora_fin&&` a ${detail.solicitud.hora_fin}`}</p><p className="sm:col-span-2"><b>Motivo:</b> {detail.solicitud.motivo||'Sin motivo registrado'}</p></div>}{user?.rol==='admin'&&<select value={detail.prioridad} onChange={(e)=>run(()=>changeReceptionPriority(detail.id,e.target.value))} className="rounded-lg border-slate-200"><option>BAJA</option><option>NORMAL</option><option>ALTA</option><option>URGENTE</option></select>}{detail.observacion&&<p className="rounded-lg border p-3 text-sm"><b>Observación:</b> {detail.observacion}</p>}{detail.resolucion&&<p className="rounded-lg border p-3 text-sm"><b>Resolución:</b> {detail.resolucion}</p>}<textarea value={text} onChange={(e)=>setText(e.target.value)} maxLength={500} placeholder={detail.estado==='EN_ATENCION'?'Observación o resolución administrativa':'Observación administrativa'} className="min-h-24 rounded-lg border-slate-200"/><div className="flex flex-wrap gap-2">{detail.estado==='PENDIENTE'&&<Button onClick={()=>run(()=>takeReceptionReferral(detail.id))}><Hand size={16}/>Tomar solicitud</Button>}{detail.estado==='EN_ATENCION'&&<><Button variant="secondary" disabled={!text.trim()} onClick={()=>run(()=>addReceptionObservation(detail.id,text))}><MessageSquarePlus size={16}/>Guardar observación</Button><Button disabled={!text.trim()} onClick={()=>run(()=>resolveReceptionReferral(detail.id,text))}><CheckCircle2 size={16}/>Resolver</Button></>}{detail.estado==='RESUELTA'&&<Button onClick={()=>run(()=>closeReceptionReferral(detail.id))}><Lock size={16}/>Cerrar</Button>}</div></div>}</></Modal>
    <ReceptionReply detail={detail} user={user} onError={setError}/>
  </div>;
}
